### ISSUE TITLE
Setup screen/page vertical scrolling not working

### ISSUE THREAD

**Issue by clach04** [Atheos/Atheos#101]
**Describe the bug**
Set up Atheos and my browser window was not very tall. The submit/save button was not visible and could not be scrolled to. Needed to increase size of browser window to "see" the button

**To Reproduce**
1. Install from scratch (delete config file?)
2. Open main page
3. resize browser to be shorted than the form length
4. can not see or us button to save/subit

**Expected behavior**
Expecting scrolling to work, and ideally a visible vertical scrollbar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows (Server Linux)
 - Browser Firefox Developer
 - Version 79.0b9 (64-bit)

**Additional context**
Atheos headrevs from git - commit dba88b5eea2d020c2de1fcb055c26a5654c7fbf6
 Tue Jul 7 22:57:33 2020

**Comment by HLSiira** [comment]
On it

-------- Original Message --------
