### ISSUE TITLE
Mising config.php

### ISSUE THREAD

**Issue by Yrosenz** [Atheos/Atheos#117]
I can be trivial for most of you, but as beginner I'd really appreciate having a config.php example .

**Comment by HLSiira** [comment]
Hey, nothing is too trivial to be asked, don't worry about it. Everyone is a beginner at some point. 

Yeah I can set one up, but may I ask why for? The installation process should create a config file for you, and if that's not happening, you might be hitting a different bug.

**Comment by Yrosenz** [comment]
So I might not be following the right instructions. 
So far have downloaded the tar file extracted inside /var/www
Changed ownership gave write access to folders as prescribed.
Created an apache virtualsite configuration.

**Comment by HLSiira** [comment]
Do your mean /var/www/html?apache defaults to inside that folder most usually

**Comment by Yrosenz** [comment]
I know but prefer to have on its own directory /var/www/atheos. As I used to do back on 80's

**Comment by kurim** [comment]
Yrosenz,
is http user owner of the atheos topfolder also, not only files inside?

**Comment by HLSiira** [comment]
@Yrosenz I actually do the same with my install of Atheos. Can I ask for some screen shots of the permissions listing of the Atheos folder? As in go into /var/www and use "ls -la"

```
liam@axios:/var/www$ ls -la
total 28
drwxr-xr-x  7 root     root     4096 Aug  2 18:20 .
drwxr-xr-x 14 root     root     4096 May 23 12:20 ..
drwxrws--- 16 www-data www-data 4096 Aug  2 18:11 atheos
drwxrws--- 11 www-data www-data 4096 Sep  3 15:36 html
```

This is the result of my install. I'm starting to think it's not a permissions issue you're having but I'd rather be 100% positive. Are you able to get to the installation screen?

**Comment by Yrosenz** [comment]
Here my screens:
<pre><font color="#4E9A06"><b>yechiel@baitpc-lx</b></font>:<font color="#3465A4"><b>/var/www</b></font>$ ls -la
total 20
drwxr-xr-x  5 www-data www-data 4096 Sep  7 19:29 <font color="#3465A4"><b>.</b></font>
drwxr-xr-x 15 root     root     4096 Sep  6 10:49 <font color="#3465A4"><b>..</b></font>
drwxr-xr-x 15 www-data www-data 4096 Sep  7 18:37 <font color="#3465A4"><b>atheos</b></font>
drwxr-xr-x  2 www-data www-data 4096 Sep  7 18:09 <font color="#3465A4"><b>example</b></font>
drwxr-xr-x  2 www-data www-data 4096 Sep  7 17:52 <font color="#3465A4"><b>html</b></font>
</pre>
<pre><font color="#4E9A06"><b>echiel@baitpc-lx</b></font>:<font color="#3465A4"><b>/var/www/atheos</b></font>$ ls -l
total 80
-rw-r--r--  1 www-data www-data 3346 Sep  7 18:27 CODE_OF_CONDUCT.md
-rw-r--r--  1 www-data www-data 4031 Sep  7 18:27 common.php
drwxr-xr-x 20 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>components</b></font>
-rw-rw-rw-  1 www-data www-data    0 Sep  7 18:37 config.php
-rw-r--r--  1 www-data www-data 1605 Sep  7 18:27 controller.php
drwxrwxrwx  2 www-data www-data 4096 Sep  7 18:27 <span style="background-color:#4E9A06"><font color="#3465A4">data</font></span>
-rw-r--r--  1 www-data www-data 1198 Sep  7 18:27 dialog.php
drwxr-xr-x  2 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>favicons</b></font>
drwxr-xr-x  5 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>fonts</b></font>
-rwxr-xr-x  1 www-data www-data 5789 Sep  7 18:27 <font color="#4E9A06"><b>index.php</b></font>
drwxr-xr-x  5 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>lib</b></font>
-rw-r--r--  1 www-data www-data 1119 Sep  7 18:27 LICENSE.md
drwxr-xr-x  2 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>modules</b></font>
drwxrwxrwx  2 www-data www-data 4096 Sep  7 18:27 <span style="background-color:#4E9A06"><font color="#3465A4">plugins</font></span>
drwxr-xr-x  2 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>public</b></font>
-rwxr-xr-x  1 www-data www-data 3308 Sep  7 18:27 <font color="#4E9A06"><b>README.md</b></font>
-rw-r--r--  1 www-data www-data  720 Sep  7 18:27 SECURITY.md
drwxrwxrwx  3 www-data www-data 4096 Sep  7 18:27 <span style="background-color:#4E9A06"><font color="#3465A4">themes</font></span>
drwxr-xr-x  2 www-data www-data 4096 Sep  7 18:27 <font color="#3465A4"><b>traits</b></font>
drwxrwxrwx  2 www-data www-data 4096 Sep  7 18:27 <span style="background-color:#4E9A06"><font color="#3465A4">workspace</font></span>
</pre>

**Comment by HLSiira** [comment]
Those look like good permissions to me, though I'd be a little worried about the others group having any permissions at all.

Are you able to see the login or installation screen when you navigate to the URL?

What does your virtual host file within Apache look like? If you don't feel comfortable posting your server configuration, please email me at liam@siira.us and we can really look through your config.php file and other things as well.


Here is my generated config.php file btw
```
<?php

//////////////////////////////////////////////////////////////////////////////80
// Configuration
//////////////////////////////////////////////////////////////////////////////80
// Copyright (c) Atheos & Liam Siira (Atheos.io), distributed as-is and without
// warranty under the MIT License. See [root]/LICENSE.md for more.
// This information must remain intact.
//////////////////////////////////////////////////////////////////////////////80
// Authors: Codiad Team, @Fluidbyte, Atheos Team, @hlsiira
//////////////////////////////////////////////////////////////////////////////80

// PATH TO ATHEOS
define("BASE_PATH", __DIR__);

// BASE URL TO ATHEOS (without trailing slash)
//define("BASE_URL", "dev.atheos.io");

// THEME : default, modern or clear (look at /themes)
define("THEME", "atheos");

// SESSION LIFETIME (e.g. 7200 = 2 hours)
define("LIFETIME", false);

// TIMEZONE
date_default_timezone_set("America/New_York");

// DEVELOPMENT MODE
define("DEVELOPMENT", true);

// EXTERNAL AUTHENTICATION
// define("AUTH_PATH", "/path/to/customauth.php");

//////////////////////////////////////////////////////////////////////////////80
// ** DO NOT EDIT CONFIG BELOW **
//////////////////////////////////////////////////////////////////////////////80

// PATHS
define("COMPONENTS", BASE_PATH . "/components");
define("PLUGINS", BASE_PATH . "/plugins");
define("THEMES", BASE_PATH . "/themes");
define("DATA", BASE_PATH . "/data");
define("WORKSPACE", BASE_PATH . "/workspace");

// END POINT URLS
define("DATAPOINT", "https://www.atheos.io/analytics");
define("MARKETURL", "https://www.atheos.io/market/json");
define("GITHUBAPI", "https://api.github.com/repos/Atheos/Atheos/releases/latest");
```

**Comment by Yrosenz** [comment]
and my atheos.conf
<pre>root@baitpc-lx:/etc/apache2/sites-available# cat atheos.conf
&lt;VirtualHost *:8080&gt;
    DocumentRoot /var/www/atheos

    &lt;Directory /var/www/atheos&gt;
        Options +Indexes +FollowSymLinks +MultiViews
        AllowOverride None
       Order allow,deny
       allow from all

    &lt;/Directory&gt;

    ErrorLog ${APACHE_LOG_DIR}/atheos.loc-error.log
    CustomLog ${APACHE_LOG_DIR}/atheos.loc-access.log combined
&lt;/VirtualHost&gt;
</pre>

**Comment by Yrosenz** [comment]
Have tried several other configurations but the result is a clear screen.

**Comment by HLSiira** [comment]
Okay so my first thoughts, I don't know what you've looked at what you haven't so I'm sorry if I'm pointing out the obvious, but if you're getting a completely blank page, I don't think it's Atheos you're having issues with, but I'm willing to be wrong.
- Have you been able to get anything aside from a blank page using this configuration?
- Is this virtualhost enabled? Your cat is from sites-available, but have you run the `a2ensite atheos.conf` command and reloaded Apache?
- The port you're listening in from that configuration is 8080, not 80, the typical web browser port, so you might need to change that unless you are pointing your browser at say `www.server.com:8080`.
- I'm also worried about a missing server name, I can't remember if that's required directive or not.

Could I also ask for some more information about your server set up? Just for the context of ensuring I'm meeting your needs.
Is this a server located inside your own house or a rented cloud server?
Could there be a firewall enabled that might be blocking your web ports?

I'm sorry if this is a lot and is starting to not seem worth it, but I don't mind spending time working though any questions you may have about this stuff, even if it has nothing to do with Atheos.

**Comment by Yrosenz** [comment]
I really think I missing something on the server.
Something with PHP I guess.
What would generate the login screen?
Does it needs mysql?

**Comment by Yrosenz** [comment]
Anyway I did installed the docket image.
Just wonder if I can ssh into it.

**Comment by HLSiira** [comment]
What does your apache error log show? `/var/log/apache/error.log`

You might not have PHP installed or enabled. Atheos doesn't utilize mysql at all, only requires Apache and PHP.

You should put an index.html file with a hello world in your /var/www/atheos directory, navigate to it to ensure your apache is configured correctly, then put an info.php with 
```
<?php
phpinfo();
?>
```
inside of it and navigate to it to test your PHP installation.

This guide is what I used a long time ago and it worked out for me: https://www.digitalocean.com/community/tutorials/how-to-install-linux-apache-mysql-php-lamp-stack-on-ubuntu-16-04

However you can skip the UFW and Mysql stuff for Atheos.

**Comment by Yrosenz** [comment]
![Screenshot from 2020-09-09 17-32-04](https://user-images.githubusercontent.com/17320075/92612827-eeab4380-f2c2-11ea-8ddb-53dab5a6c69b.png)
