### ISSUE TITLE
Can't create new project

### ISSUE THREAD

**Issue by 4everZIP** [Atheos/Atheos#121]
Hi! I was using preovious releases of Atheos for a long time. Everything was great, thank you!

On 4.2.0. I can't create new project with absolute path on fresh install of Atheos.

See the screenshot with console errors https://yadi.sk/i/hBu7_-FtOCjG4Q

Appreciate any solution

**Comment by HLSiira** [comment]
I'm not at home right now, so can't really dig into it but my first thought is a permission issue. Atheos runs as your web-user on the server and typically the web user doesn't have access to much of anything outside the /var/www, especially /home.

Have you checked the permissions for the folder path?

Can you create projects elsewhere successfully? Or not at all?

**Comment by 4everZIP** [comment]
Thank you for a fast reply! I know about permission issue since Codiad.

I use Vesta control panel so my home folder is just the same as native web server root folder.

For test purpose I downloaded Atheos 4.0.0 and it creates new project with the same absolute path just fine.
https://yadi.sk/i/hifILD4o8EXgYA

In Codiad I manage to use absolute paths by setting the constant in config.php "WHITEPATHS".

**Comment by HLSiira** [comment]
I could never tell what the point of the white paths in Codiad was aside from limiting the user from using Codiad however they wanted sadly, so it was removed from Atheos. Atheos will let you create whatever you want whenever you want as an admin.

What about downloading the most recent branch from master? Does that also prevent you from creating new absolute project paths?

I'll have to check out Vesta, it sounds pretty neat.

**Comment by 4everZIP** [comment]
Branch master works the same as 4.2.0 Grandmaster. Same errors in the console prevent creating a new project with absolute paths.

Just tested 4.2.0 Chamberlain - works fine with absolute paths

**Comment by HLSiira** [comment]
HA ha .... ha. I'm an idiot. I know what the bug is and hopefully will have it fixed asap.

I reread your console messages and realized that since you're using another language as your keys, it won't work since I had the brilliantly stupid idea of using the innerText of a button to hold the reference to the name of the function it calls.

I can't believe that this bug hasn't popped up earlier.

**Comment by 4everZIP** [comment]
Oh, it was so easy)
I change the innertext of the button to "Yes" and it works fine.

I didn't do anything with language. Since 4.2.0 Grandmaster, text on this buttons shows in my system language automatically.

https://yadi.sk/i/l0LFkuhTDxzPXw

Thank you for solution!
