### ISSUE TITLE
Feature request: Links and versions

### ISSUE THREAD

**Issue by ScrumpyJack** [Atheos/Atheos#125]
Can we have link to this github repo and the version installed somewhere on the Atheos login page?

**Comment by HLSiira** [comment]
![Annotation 2020-09-07 115620](https://user-images.githubusercontent.com/792284/92404319-397d5d80-f101-11ea-982b-85bd80c78257.png)


How's this?

**Comment by ScrumpyJack** [comment]
Perfect, thank you

**Comment by HLSiira** [comment]
Sweet, it will be in the next push to master
