### ISSUE TITLE
Installation Troubles

### ISSUE THREAD

**Issue by CM55555** [Atheos/Atheos#127]
I've been trying the instructions at https://www.atheos.io/docs/installation/ubuntu. (I'm using php7.3, not 5)

I'm doing this on a Raspberry Pi 4 (8gb), with Raspberry Pi OS 1.4.

I extracted the released ZIP for 4.3.0 under /var/www/html/, and for testing, applied chmod 777 -R for the whole folder. (I'm running this internally over LAN.)

However, when I open up my browser, I only see a blank page. config.php is empty, and navigating manually to index.php inside the Atheos folder also gives a blank page.

I also tried installing the 4.2.0 release instead. With that, I am able to access the install page, but after completing all of the required fields (username, password, time zone, etc.), I am left at a blank page with no indication (from the browser, nor from running top at the command line) that the installation process has started.

Thanks for any suggestions. I suspect the issue is on my end, but as far as I can tell, PHP 7.3 is working with apache2 (tested with some simple php test pages).

EDIT: 4.1.0 appears to install correctly. I'm not sure why yet.

**Comment by HLSiira** [comment]
What kind of messages do you have, if any, in the apache error log file located at /var/log/apache/error.log?

**Comment by CM55555** [comment]
> What kind of messages do you have, if any, in the apache error log file located at /var/log/apache/error.log?

There are a great deal of errors, many of which are repeated.
`
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Sep 08 03:37:51.097172 2020] [mpm_prefork:notice] [pid 18694] AH00163: Apache/2.4.38 (Raspbian) configured -- resuming normal operations
[Tue Sep 08 03:37:51.097221 2020] [core:notice] [pid 18694] AH00094: Command line: '/usr/sbin/apache2'

PHP Warning:  include(major/config.php): failed to open stream: No such file or directory in /var/www/html/Atheos/components/codegit/templates/codegit.php                                                          on line 28
PHP Warning:  strpos(): Empty needle in /var/www/html/Atheos/common.php on line 425
-bash: syntax error near unexpected token `('
`

If you think it'd be easier, I could try purging everything and starting the install over from scratch, so I can be clear about what errors are associated with trying to install 4.3.0.

**Comment by HLSiira** [comment]
Those are some very strange error messages. The only one that stands out to me is the call to mb_substr() in the path converter.

Would you be opposed to doing a completely fresh install of the most recent build from Master branch and seeing how that one works for you, and reporting any error messages?

It honestly looks like somehow your computer is trying to use both installations at the same time but that also doesn't seem right to me. Meanwhile, I'll set up my raspberrypi as you have yours and see what issues I run into.

**Comment by HLSiira** [comment]
@CM55555 I was able to reproduce the error on my raspberryPI. You need to install php's mbstring in order for it to work.
You can check to see if it's installed by typing `php -m | grep mb`. If it returns no results, it's not installed.

In order to install it, run `sudo apt install php7.3-mbstring` (or in my case `sudo apt install php7.0-mbstring`), then restart apache with `systemctl restart apache2`.

I tested this using the lastest pull from master but this fix should work for any version.

**Comment by hacebe** [comment]
I have faced the same problem, but on my Ubuntu 18.04 Server. The installation screen is white. I got a 500 error and the apache logs tells its a problem with MatthiasMullie's Minify class. I have mbstring installed and enabled too.

**Comment by HLSiira** [comment]
Does it give the same undefined function error? If so, then something is wrong with your mbstring installation, maybe you installed it for PHP7.0 but Apache is running your PHP7.3 or something like that.

If not, what function is it claiming an error with?

**Comment by hacebe** [comment]
Sorry. its not a "undefined function" in my case, but this one 

`PHP Fatal error:  Uncaught Error: Class 'MatthiasMullie\\Minify\\Exceptions\\IOException' not found in /var/www/html/Atheos/lib/minify/Minify.php`

I'm using both php7.2 and php7.2-mbstring

**Comment by HLSiira** [comment]
I am sorry you're dealing with this. What's the full error log? The IO exception was removed from minify but it shouldn't be popping off unless there is a permission error or some other form of writing error.

**Comment by CM55555** [comment]
> @CM55555 I was able to reproduce the error on my raspberryPI. You need to install php's mbstring in order for it to work.
> You can check to see if it's installed by typing `php -m | grep mb`. If it returns no results, it's not installed.
> 
> In order to install it, run `sudo apt install php7.3-mbstring` (or in my case `sudo apt install php7.0-mbstring`), then restart apache with `systemctl restart apache2`.
> 
> I tested this using the lastest pull from master but this fix should work for any version.

Thanks! This worked for me.

**Comment by KenCOCOCO** [comment]
> I am sorry you're dealing with this. What's the full error log? The IO exception was removed from minify but it shouldn't be popping off unless there is a permission error or some other form of writing error.

I am experiencing this issue with my Raspberry Pi running Apache 2 with PHP 7.3. PHP-mbstring is enabled. Lots of errors.

**Comment by HLSiira** [comment]
Can you post the full error log from /var/log/apache/error.log?

**Comment by KenCOCOCO** [comment]
> Can you post the full error log from /var/log/apache/error.log?

Hey! It seems I reinstalled my Raspbian Desktop on the RPI SD card and installed PHP with "FPM", then installed php-mbstring. Seems to work perfect now! Thank you.

**Comment by haexperts2020** [comment]
Similar issue. Fresh install Ubuntu 20.04 with PHP 7.4, installed Atheos from master
Try to load index.php and I get a black screen. View Source stops rendering the page at ""

error.log shows a bunch of errors related to minify:
`PHP Fatal error:  Uncaught Exception: The file "public/fonts.min.css" could not be opened for writing. Check if PHP has enough permissions. in /var/www/atheos/vendor/minify/Minify.php:475\nStack trace:\n#0 /var/www/atheos/vendor/minify/Minify.php(235): MatthiasMullie\\Minify\\Minify->openFileForWriting()\n#1 /var/www/atheos/vendor/minify/Minify.php(152): MatthiasMullie\\Minify\\Minify->save()\n#2 /var/www/atheos/traits/cls.source.php(159): MatthiasMullie\\Minify\\Minify->minify()\n#3 /var/www/atheos/traits/cls.source.php(119): SourceManager->loadAndMinifyCSS()\n#4 /var/www/atheos/traits/cls.source.php(112): SourceManager->loadAndMinify()\n#5 /var/www/atheos/index.php(48): SourceManager->echo()\n#6 {main}\n  thrown in /var/www/atheos/vendor/minify/Minify.php on line 475`

Files and folders have correct permissions and owner group. A simple temp.php file renders phpinfo() just fine. 

And yes I have mbstring installed and enabled. 

Any ideas?

**Comment by haexperts2020** [comment]
That did the trick. Thanks!
