### ISSUE TITLE
Feedback request on new logo

### ISSUE THREAD

**Issue by HLSiira** [Atheos/Atheos#128]
Hey there,

Wanted to ask for some thoughts on a new logo. The current one is way too busy, especially as a favicon so I made this one. Looks pretty nice in my opinion but since I won't be the only one staring at it all day potentially, I wanted to ask for feedback.

![atheos_logo ](https://user-images.githubusercontent.com/792284/93024672-0be35900-f5c6-11ea-8cf2-2c5cec872beb.png)

**Comment by kurim** [comment]
Hi Siira,

i think it's ok but how about do it more like this: (sorry just for illustration done it in paint.net :D
![image](https://user-images.githubusercontent.com/1880220/93178975-559e8180-f735-11ea-8306-a2d48d946ea5.png)

or like it is on the lower part to have it realy symmetric
![image](https://user-images.githubusercontent.com/1880220/93179405-ee350180-f735-11ea-8d3c-2527f98b0755.png)

Also it looks like the lower lines are longer than the surrounding ones, might be just an optical illusion...

![image](https://user-images.githubusercontent.com/1880220/93178797-05bfba80-f735-11ea-80bc-f5348240bd1d.png)

**Comment by HLSiira** [comment]
Lol yeah I noticed those little forks at the bottom once it start moving, need to fix them soon.

I kind of like the asymmetry of it but it hasn't quite won me over yet, as it is now, it's still a little too busy in the Favicon. The middle option is pretty neat looking though, might be worth playing with that idea more.

**Comment by kurim** [comment]
May be w/I Outline as favorite icon and rest as logo
