### ISSUE TITLE
"Use of undefined constant path", AKA Marketplace crash

### ISSUE THREAD

**Issue by TheCurle** [Atheos/Atheos#129]
**Describe the bug**
When installing anything from the Marketplace, from a fresh install of Grandmaster, the window freezes and halts taking any input from the user.

At the same time, the following error is printed to the PHP log:

```
PHP Fatal error:  Uncaught ErrorException: Use of undefined constant path - assumed 'path' (this will throw an Error in a future version of PHP) in <FOLDER>\ide\components\market\class.market.php:167
Stack trace:
#0 <FOLDER>\ide\components\market\class.market.php(167): {closure}(2, 'Use of undefine...', '<FOLDER>\\ide\\co...', 167, Array)
#1 <FOLDER>\ide\components\market\controller.php(39): Market->install('Minimap', 'plugins', 'Utility')
#2 <FOLDER>\ide\controller.php(44): require('C:\\sites\\ide\\co...')
#3 {main}
  thrown in <FOLDER>\ide\components\market\class.market.php on line 167
```

**To Reproduce**
1. Download the latest release, currently titled 'Grandmaster'
2. Extract the zip to a folder visible from a web server
3. Make the appropriate folders and files writeable from the server
4. Add a user and project according to the setup
5. Immediately add any package from the Marketplace.

**Expected behavior**
It installs the addon and releases control back to the user.

**Screenshots**
![image](https://user-images.githubusercontent.com/42079760/93132142-10df0000-f6cd-11ea-8c55-78fe3a6fc653.png)

**Desktop (please complete the following information):**
(The client)
 - OS: Windows 10 2004
 - Browser: Firefox 
 - Version 80.0.1

**Additional context**
The tab running the window completely halts. No buttons respond, the only way out is to close the tab and reopen the IDE.

As well as the above log being put into the PHP log, the following is printed to the console:

XHRPOST https://<SITE>/controller.php
[HTTP/1.1 500 Internal Server Error 1385ms]

**Comment by HLSiira** [comment]
Wow, missing a single dollar is quite the mistake. I fixed it in the most recent push to the development branch, and thank you for such a detailed issue, I was able to replicate the issue perfectly.

**Comment by TheCurle** [comment]
Installing Marketplace addons in development branch still causes an error. I will open a new issue as this error is different.
