### ISSUE TITLE
oX is undefined, AKA Settings Error

### ISSUE THREAD

**Issue by TheCurle** [Atheos/Atheos#130]
**Describe the bug**
When changing any settings inside a fresh install of Grandmaster, the change is ignored and the following error is printed to the browser console.

There is no error printed to the web server logs.

**To Reproduce**
1. Download and unzip the latest Grandmaster release
2. Setup a new user and project according to the setup prompt
3. Immediately log in and try to change any settings. For example:
4. Navigate to Textmode
5. Add a new extension and leave it at the default "apab handler"
6. Close the settings window and reopen it, noting the text "Settings are automatically saved." in the bottom right corner of the settings window
7. See that the new extension has been removed.

**Expected behavior**
The setting change to save and persist to the next opening of the window.

This is the error printed to the console:
```
Uncaught TypeError: oX(...) is undefined 
    saveExtensions https://<SITE>/components/textmode/init.js:144  
    onclick https://<SITE>/:1  
init.js:144:17  
    saveExtensions https://<SITE>/components/textmode/init.js:144  
    onclick https://<SITE>/:1
```

**Desktop (please complete the following information):**
 - OS: Windows 10 2004
 - Browser Firefox 
 - Version 80.0.1

**Additional context**
The above example is given for changing a textmode setting, but the same applies for any setting you try to change.

**Comment by HLSiira** [comment]
I was able to reproduce on textmode, but not in any other setting changes, although it could be if you were changing the textmode and then trying to change another setting, the system failed to register after failing on textmode

**Comment by TheCurle** [comment]
Okay. Thanks for the quick reply to both issues! I've been following Codiad since it's conception, and back then it was a security nightmare so i never went anywhere with it.

Glad to see Atheos is actively developed.

If i see any more issues, I'll drop a bug report here.

**Comment by TheCurle** [comment]
This error is indeed fixed. Thanks!
