### ISSUE TITLE
[Development] Unable to remove installed extensions AKA, rmdir is unhappy

### ISSUE THREAD

**Issue by TheCurle** [Atheos/Atheos#133]
**Describe the bug**
When removing an installed extension, an error is thrown and the UI hangs.

**To Reproduce**
1. Clone development branch
2. Point webserver at the cloned folder
3. Give appropriate permissions as necessary
4. Perform the normal Atheos setup
5. Log in
6. Navigate to the Marketplace and install an addon, eg. MiniMap
7. Use the addon at least once
8. Navigate back to the Marketplace and uninstall the addon you installed in step 6.
9. Watch helplessly as the tab freezes

**Expected behavior**
The addon is uninstalled and control is handed back to the user

**Additional context**

As the tab freezes, the following text is outputted to the PHP log:
```
PHP Fatal error:  Uncaught ErrorException: rmdir(<FOLDER>plugins/MiniMap): Directory not empty in <FOLDER>\traits\helpers.php:145
Stack trace:
#0 [internal function]: {closure}(2, 'rmdir(<FOLDER>', '<FOLDER>\tr...', 145, Array)
#1 <FOLDER>\traits\helpers.php(145): rmdir('<FOLDER>/pl...')
#2 <FOLDER>\components\market\class.market.php(183): Common::rDelete('<FOLDER>/pl...')
#3 <FOLDER>\components\market\controller.php(46): Market->remove('MiniMap', 'plugins')
#4 <FOLDER>\controller.php(49): require('<FODLER>\co...')
#5 {main}
  thrown in <FOLDER>traits\helpers.php on line 145
```

**Comment by HLSiira** [comment]
I fixed the hanging issue but it's going to take some time to fix the removing issue, it's for some reason using different letter case for the installation vs the removal and it's going to take a bit to track down the disconnect.

**Comment by HLSiira** [comment]
I'm fixing this by updating the plugins and enforcing case sensitivity for urls to plugin names. The names are used frequently enough as hard coded things that development would be difficult if it wasn't consistent.
