### ISSUE TITLE
Editor Markup not always loaded

### ISSUE THREAD

**Issue by kurim** [Atheos/Atheos#139]
**Describe the bug**
Sometimes editor markup does not work.

**To Reproduce**
1. leave documents open
2. logout
3. login and sometimes it dont load the markups
4. press F5 to fix it

**Expected behavior**
Should alwayse load markups

**Screenshots**
![image](https://user-images.githubusercontent.com/1880220/95467227-80b77200-097d-11eb-9a15-39f0dca397b7.png)
should look like:
![image](https://user-images.githubusercontent.com/1880220/95467286-9036bb00-097d-11eb-9285-ad871e49cc28.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Chrome
 - Version 86

**Comment by HLSiira** [comment]
I've noticed this bug as well, I'll try to trace through the syntax code and see what's getting hung up or stalled.

**Comment by HLSiira** [comment]
Have you had this happen in a while? I haven't had it happen to me in a long time now.

**Comment by kurim** [comment]
Not realy, but I lately did not use it very often.
