### ISSUE TITLE
Auto-indentation doesn't works with spaces

### ISSUE THREAD

**Issue by TheFax** [Atheos/Atheos#140]
**Describe the bug**
Atheos uses TAB when is auto-indenting code, whatever the configuration set by the user.

**To Reproduce**
1. Set: Settings -> Editor -> Soft-tabs to DISABLE
2. Create a new file and name it "test.py"
3. Paste this code:
```
import sys
    def test():
        pass
```
(note that I used 4 spaces for every indentation level.
4. Place the cursor after the colon, and press Enter
5. This is the result:
```
import sys
    def test():
    	
        pass
```
Atheos indented the new line with 4 spaces + 1 tab. Mixing tab and spaces is not allowed in Python 3.

**Expected behavior**
Atheos should indent with 4 spaces + 4 spaces and should not uses tabs.
Atheos should auto-learn that I'm using spaces to indent my document. 

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox 81

**Comment by HLSiira** [comment]
So I can reproduce and verify this bug, but I can't offer up an easy solution for a while. The problem doesn't appear to be with Atheos but rather with the [Ace Editor](https://github.com/ajaxorg/ace) that Atheos utilizes. I'm going to have to dig through their repo and see if anyone else has found a fix but with 600+ issues, it might take me a while.

If you're curious, you can interact with the Ace Editor directly a bit more by using Ctrl + Comma to open up it's session menu, but note that the changes you make there won't be saved, or carry over to other editor tabs.

The auto learn is an interesting idea though, I'll have to think about it. I'm assuming you mean such if you past code into Atheos, it will either correct it to the proper indentation, or start using the majority indentation found in the file.

Let me know if you happen to run into a fix in the settings.

**Comment by HLSiira** [comment]
I'm going to close this issue if that's cool. I've been messing around with it for a while now and digging into Ace a little bit and it's an issue that's outside of scope for the project right now and probably will be for a while.

I can think of a few cheap work arounds, like the Atheos-Beautify plugin will convert tabs/spaces based on user preference but there isn't support for C or Python yet on it.
