### ISSUE TITLE
How to upgrade Atheos?

### ISSUE THREAD

**Issue by TheFax** [Atheos/Atheos#141]
Please add a section in [README.md](https://github.com/Atheos/Atheos/blob/master/README.md) providing informations about **how to upgrade Atheos without loosing settings, documents/data and accounts**.

Thankyou.

**Comment by HLSiira** [comment]
Good idea. I'll have to add one. I'm actually working on an auto update feature but it's taking longer than I'd like.

For now, you can find a little more details in the documentation found [here](https://www.atheos.io/docs/updating)
