### ISSUE TITLE
Rename Project

### ISSUE THREAD

**Issue by kurim** [Atheos/Atheos#142]
**Describe the bug**
Unable to rename a project.

**To Reproduce**
1. Open Project list
2. Select project you want to name
3. Rename it, system shows as renamed
4. See error, project is not renamed

**Expected behavior**
It should rename the project

**Comment by HLSiira** [comment]
Probably due to changing the way Projects are saved and loaded, shouldn't be too hard to fix. 

Work has been picking up quite a bit the last few months so I haven't had much time to work on Atheos, hopefully I'll be able to at least address this soon.
