### ISSUE TITLE
support for vueJs

### ISSUE THREAD

**Issue by emuter** [Atheos/Atheos#143]
please provide support for vue js code syntex

**Comment by HLSiira** [comment]
In what way? Javascript syntax highlighting and linting is already a part of the default Atheos install so I'm a bit confused on what specifically you're looking for.

If you don't mind, what were you wanting to accomplish that you realized Atheos doesn't provide support for specifically? Thank you.

**Comment by emuter** [comment]
Thanks for replying. And sorry about the lack of details in the comment.

What i wanted to tell was if i open a vue file every text, element, code, script etc.. are only visible in white color.
Perhaps it works as intended and im just lacking some setting or adjustment, maybe. Yet, i would really appreciate if that worked.

Thanks once again for the best of contributions you are providing. Wishing you well.

**Comment by HLSiira** [comment]
If you open the settings, you can add the file extension of Vue to use JS highlighting by default when you open the file, and at the bottom of the screen, you can also select the modes, but yeah. What is the file extension and mode that you would like for VueJS and I can make it a default setting for future installs?

**Comment by emuter** [comment]
Thats great
Please add the extension ".vue"  for future release.
Tc
