### ISSUE TITLE
Keybinding for Apple MacOS keyboard

### ISSUE THREAD

**Issue by chadpriddle** [Atheos/Atheos#148]
Accessing Atheos with a mac. Came from Codied and decided to try this update. 

Right now the keyboard binds to the "control" button. How can I get it to bind to the "Command" button on a mac keyboard? 

Found the /modules/keybind.js file but cannot figure out how to get the javascript to listen for the command button.

Currently Command + S wants to save the webpage in Chrome, not ideal. 

Thanks

**Comment by HLSiira** [comment]
Oof, sorry about that.

We'll probably need to figure out which keycode Mac uses for CMD when it hits the browser and ensure that it's properly registered, it'll be near the bottom of that exact file, the key bind one.

I'll look through it once I get home and try to push a fix on as soon as possible, unless you find out first.

**Comment by chadpriddle** [comment]
I found this article but not sure where to put it in the handler function. The interesting thing is that codied worked with the command + s key press. Assuming it was part of the JQuery libs that are now gone. 

https://stackoverflow.com/questions/3902635/how-does-one-capture-a-macs-command-key-via-javascript

**Comment by HLSiira** [comment]
Do you want to fix it and make a pull request? I can if you don't.

If you look at the keybind.js file, near the bottom in the handler, you'll see line 125: `} else if (bind.cmd.includes('ctrl') !== e.ctrlKey) {`

You'll need to change that line to also check if the metakey is utilized.

**Comment by chadpriddle** [comment]
Works for me thanks

**Comment by HLSiira** [comment]
Anytime, let me know if you come across any other issues.

**Comment by chadpriddle** [comment]
Weird it work for a day after I modified that line of code and refreshed and now today the command key does not work

**Comment by HLSiira** [comment]
The only reason I can think of is that your cache somehow reverted back to the original code, try to view the source code in browser and see if You can find out if it's useing command key or not

**Comment by HLSiira** [comment]
Are you still having this issue?

**Comment by chadpriddle** [comment]
Yes, still getting the same issue. Do you have a mac to test?

**Comment by HLSiira** [comment]
No I don't sadly, but I think it's because I made a typo in the original fix, a lowercase K vs an uppercase K in e.metaKey. The correct version should be in master now.

**Comment by haexperts2020** [comment]
Its working now. Thanks!
I'll confirm again tomorrow

**Comment by chadpriddle** [comment]
Its working great now. Thanks!
