### ISSUE TITLE
Increase session time for a login

### ISSUE THREAD

**Issue by haexperts2020** [Atheos/Atheos#150]
Is there a remember session value or cookie to be increased? I have this on a dev server where i'd like to stay logged in for a week or so. I have an extensive laravel folder tree on the side that always collapses after the session expires. Minor inconvenience

**Comment by HLSiira** [comment]
Yes, but it's untested, as in I've just never tested it. Within your config.php file, you should have a line `define("LIFETIME", false);`. If you set that to a value in MS, it will be used to set the php.session.lifetime on [L53 of common.php](https://github.com/Atheos/Atheos/blob/master/common.php#L53).

Theoretically you could set it to equal `604800000` but my worry is that the [checkSession function](https://github.com/Atheos/Atheos/blob/master/traits/checks.php#L60) would somehow glitch out, but I can't see how, or more likely is that the Apache.conf/PHP.ini file has some sort of lock or maximum session time that'd you'd have to override.

I'll look into it and see if I hit any hurtles, but what I might do is try to see if I can _save the state_ of the file tree periodically and load on login?
