### ISSUE TITLE
SVN support

### ISSUE THREAD

**Issue by HalliHalloSchatz** [Atheos/Atheos#154]
**Is your feature request related to a problem? Please describe.**
I have only a Subversion repository

**Describe the solution you'd like**
Integration with svn/subversion are nice

**Additional context**
THANK YOU

**Comment by HLSiira** [comment]
I wouldn't be opposed to adding SVN integration but I don't know if I have enough experience with SVN. CodeGit detects a repo by looking for `.git` folders, and then just runs the relevant commands as the web user within the repo folder when you click, so if you could describe more about a typical SVN repo, and it's command usage, I might be able to work something out in the longer term, but I think you might be able to add that feature faster than I could.

**Comment by HalliHalloSchatz** [comment]
I found this for the old Codiad: https://github.com/tholum/Codiad-SVN
I am not a programmer, I am a linux administrator and use this for my scripts. I like the web based editors and it would nice to manage all my scripts with it...

but the svn commands are really really simple
svn co - checkout need the repo url for inital update/checkout
svn up - update 
svn ci - commit

**Comment by HLSiira** [comment]
I won't be able to implement this due to the time requirements of work and trying to code. I'll add it to the backlog of my notes, but it probably won't make it into a feature set for a very very long time.

**Comment by mach7** [comment]
> I won't be able to implement this due to the time requirements of work and trying to code. I'll add it to the backlog of my notes, but it probably won't make it into a feature set for a very very long time.

Are your notes available somewhere if someone had some free time to work on things and wanted to lend a hand?
