### ISSUE TITLE
'updateACL' feature broken by a small bug

### ISSUE THREAD

**Issue by fdennemont** [Atheos/Atheos#155]
**Describe the bug**
The 'updateACL' feature is currently not doing anything.

**To Reproduce**
1. You need at least two users and two projects.
2. Log into Atheos using an admin account.
3. In the right side bar, click 'Users'.
4. Click on another user's 'Projects' button.
5. Select 'Only Selected Projects' in the list.
6. Check only one project in the list.
7. Click 'Update' button.
8. The user still has access to all projects.

**Expected behavior**
The user has access only to the selected project.

**Additional context**
This seems to be caused by a small typo in components/user/controller.php. Everything seems to work after applying this diff:
```diff
--- a/components/user/controller.php
+++ b/components/user/controller.php
@@ -120,10 +120,9 @@ switch ($action) {
                }
                if (!$username) {
                        Common::send("error", "Missing username.");
-
-                       $userACL = POST("userACL");
-                       $User->updateACL($username, $userACL);
                }
+               $userACL = POST("userACL");
+               $User->updateACL($username, $userACL);
                break;

        //////////////////////////////////////////////////////////////////////////80
```

**Comment by HLSiira** [comment]
sigh... I read the headline of this issue and went through the entire debugging process to find out that if I had just read the issue fully, you already found the fix. 

It's added and I'll be merging soon.

**Comment by fdennemont** [comment]
Hey, sorry for hiding this info at the end.
Thanks for your great work :)
