### ISSUE TITLE
Fresh install problems

### ISSUE THREAD

**Issue by baddiedev** [Atheos/Atheos#157]
**Describe the bug**
I cloned a new copy today. When I first load the page to install and every time I submit the new login details, a bunch of PHP error messages flash before I'm brought back to the new login dialog again.

**To Reproduce**
1. Clone new copy into new folder
2. Change folder permissions as per fresh install
3. Navigate in browser to folder to launch the installation
4. PHP error messages flash before new login dialog appears
5. Complete new login and project details and submit
6. Page refreshes including flashing PHP errors again before displaying new login dialog again.
7. New login not successful and no Atheos error message displayed
8. Check for presence of config.php to change permissions as per fresh install and find it was not created

**Expected behavior**
IDE should launch for the first time and a config.php file should be created

**Desktop**
OS: ChromeOS/Linux (Debian, Xampp)
Browser: Chrome
Version: 88

**Additional context**
Console and apache access_log reports 404 errors for the following files:
```
  /public/fonts.min.css
  /public/modules.min.js
  /public/plugins.min.css
```
Console reports:
```
Uncaught ReferenceError: oX is not defined
    at init.js:21
    at init.js:129
```
Apache errors_log reports the following errors:
```
  PHP Notice:  Undefined variable: minifiedFileName in /home/[USER]/.atheos/public/class.sourcemanager.php on line 120
  PHP Warning:  file_put_contents(): Filename cannot be empty in /home/[USER]/.atheos/public/class.sourcemanager.php on line 147
```

**Comment by HLSiira** [comment]
Oh easy fix, I must have forgot to change something in the public/source.manager.php. I'll have it fixed and pushed into master in maybe an hour, sorry about that.

Thank you for the supreme detail in the issue though, really helped
