### ISSUE TITLE
Problem with install password

### ISSUE THREAD

**Issue by asteroids1975** [Atheos/Atheos#161]
Hello!
I was looking for an alternative to Codiad and found this awesome project.
I installed it and had problems to login after first installation !!
So I start looking for the issue and I found it on the installation script:

https://github.com/Atheos/Atheos/blob/f7c4f9f526d0e847c8e7e3c663062cf0838f7a36/components/install/process.php#L30

It takes the username as password.

Bye!

**Comment by HLSiira** [comment]
Oh thanks man, I will have that fix pushed to master asap. Sorry about the typo!
