### ISSUE TITLE
Considering changing licenses to GPLv3

### ISSUE THREAD

**Issue by HLSiira** [Atheos/Atheos#167]
I am considering attempting to change from the MIT to the GPLv3 license for Atheos mainly for the goal of ensuring that contributions to Atheos remain in the main Atheos repository, and keeping the code open. After coming across a few too many horror stories, it's wormed into my brain as something I should at least consider. This is my main pet project and I'd hate to see EvilCorp Inc. ruin something I'm very passionate about.

I've been reading a lot about the various licenses and think [this article](https://exygy.com/blog/which-license-should-i-use-mit-vs-apache-vs-gpl/) most simply explains the differences between the big three for anyone unfamiliar.

I'm not 100% sure if I'm legally allowed to change the license with this originally being a fork of Codiad, but from my understanding, it's reasonable that at this point, I could remove Codiad references if forced due to just how much of the source, structure, and design has changed, but I'd hate to take that step because it's important to me to ensure that the people who helped this project get the credit they deserve; I reached out to a few non-profit specialty orgs to ask for advice.

I'd like to heard from anyone willing to speak on the issue of what they think and what they'd like to see happen and why.

The actual decision of doing the change is a LONG way off, so no rush. Thank you for your help/interest in this project!

**Comment by kurim** [comment]
Hi Siira,

you may already found this post about changing license:
[Can you change code distributed under the MIT license, and re-distribute it under the GPL license?](https://softwareengineering.stackexchange.com/questions/105912/can-you-change-code-distributed-under-the-mit-license-and-re-distribute-it-unde)
[Relicensing an MIT licensed project under the GPL that has non code contributions from others](https://opensource.stackexchange.com/questions/5832/relicensing-an-mit-licensed-project-under-the-gpl-that-has-non-code-contribution)

So basicly I think it is possible.

**Comment by HLSiira** [comment]
From what I've read, I have to maintain both copies of the licenses and that seems excessive. Honestly it seems like one of those things of "Just do it" and see what happens

**Comment by WebCrew** [comment]
You can try to chat with the original main developer about it. If he will change the license then all should be fine. For my opinion I think the original developer of Codiad will habe nothing against it - I think he is happy about your efford and about that his work was not for nothing.

Its worth trying :)
