### ISSUE TITLE
Deleting a folder deleted everything starting with the same name

### ISSUE THREAD

**Issue by baddiedev** [Atheos/Atheos#168]
**Describe the bug**
Using the File Manager window, I right-click > deleted a folder named 'wp'. This resulted in all folders AND files starting with 'wp' in that folder to be deleted, not just the folder I selected.

**To Reproduce**
Steps to reproduce the behaviour:
1. Within a folder, create another folder named 'wp' (or anything I suppose) and give it some content (files and folders)
2. Create several more folders and files with names starting with 'wp'
3. Right-click > delete the folder that's just called 'wp'
4. See hours worth of work vanish. :(

**Expected behavior**
Just the folder (and its contents) that I selected with right-click > delete should be deleted 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Local: Chrome OS / Server: Linux
 - Browser: Chrome
 - Version: 89

**Additional context**
I had installed wordpress to a sub folder to build it out before migrating it to the root. I called the subfolder 'wp' and was trying to delete that folder, having completed the migration. All of wordpress files and folders at that level begin with 'wp' so both the original files AND the migrated copies all vanished.

**Comment by HLSiira** [comment]
Oh my goodness, I am so sorry. I've never ran into a bug like that in  all the time I've been working on Atheos.

I will look into it ASAP and let you know, thank you for letting me know.

**Comment by baddiedev** [comment]
Don't worry. I put it down to one of those things. Then, just after I did, I found myself in dev nirvana. An automatic backup of my site happened 5 minutes after I stopped working on it last night. :8)
