### ISSUE TITLE
One small thing: The link to the Install WIKI is down

### ISSUE THREAD

**Issue by WebCrew** [Atheos/Atheos#169]
Hi @HLSiira 

- I was just visiting the homepage and found that **the link to the install and documentation WIKI leads to 404**.
https://www.atheos.io/docs/installation/

- and the screenshot at the Readme.md is missing - here you go / it is the one of your homepage.

![atheos](https://user-images.githubusercontent.com/12986067/113449336-e6049100-93fd-11eb-920c-4aa5d45b76d7.jpg)

Best regards and **huuuuge thanks** for your awesome job!

**Kind regards**, Andy :)

**Comment by HLSiira** [comment]
Oh wow, thank you for letting me know. I fixed it in the most recent push to master.

Thank you for your kind words as well, I'll try my best to keep Atheos awesome!
