### ISSUE TITLE
update docker image

### ISSUE THREAD

**Issue by MohamedElashri** [Atheos/Atheos#170]
**Describe the bug**
Not really a bug but the DockerHub image is not up to dated and still with version 4.2. 
**To Reproduce**

run 
```docker run --name atheos --rm -p 8080:80 -d hlsiira/atheos``` 
**Expected behavior**
The version should be the latest version. Instead, you will get an old version. 

**Additional context**
This can be automated via GitHub action.

**Comment by HLSiira** [comment]
Thank you. I'll try to update it as soon as I can later today, def going to look into the github action though

**Comment by ScrumpyJack** [comment]
@HLSiira Can we see your docker build file?

**Comment by HLSiira** [comment]
@ScrumpyJack oh absolutely lol. I haven't had time to learn Docker so I asked a friend to make it. There is a separate repo for it though: https://github.com/Atheos/Atheos-Docker
