### ISSUE TITLE
Considering adding the codiad macro plugin

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#171]
**Is your feature request related to a problem? Please describe.**
I need to execute some .sh/.php files within Atheos (I have custom push2prod scripts that manage syncing, caching and minifying features).

**Describe the solution you'd like**
With Codiad I use the Codiad-Macro plugin (https://github.com/daeks-archive/Codiad-Macro) which works very well and is very usefull. I've made me 2 macros that are executable with a simple right click on any file : "Execute as SH" and "Execute as PHP" (please see the screenshots attached).
![2021-04-14 10_41_14-Codiad](https://user-images.githubusercontent.com/3533283/114681052-0ee62980-9d0e-11eb-8faf-73c4426c16cd.png)
![2021-04-14 10_42_44-Codiad](https://user-images.githubusercontent.com/3533283/114681193-33da9c80-9d0e-11eb-8a09-5160b28b3950.png)

**Additional context**
The only way to execute SH or PHP files within Atheos today is to use the Terminal plugin which is not as simple as a right click on a file. Furthermore the Terminal plugin doen't work well (it doesn't manage the copy/paste feature correctly, nor the cursor positionning or the autocomplete feature with tab hit).

**Comment by HLSiira** [comment]
Oh yeah, this seems awesome.

When you say considering, are you asking me to or planning to do so yourself? I don't mind trying to do it, it seems like a smaller plugin, although I'd add the ability to show specific macros based on file extension. I don't want to duplicate efforts though.

**Comment by tchavot** [comment]
This a a very powerful plugin as possibilities are infinite. You can easily create a macro to unzip a file, to add a write/execute permission on a file, to execute a file, etc.

If you can do it it would be wonderful! I'm not sure to be good enough to dive into it...

The ability to filter macros on file extension would be great indeed!

Also have you planned to add the FileUse plugin (to be notified when another user has the same file currently opened and to avoid the case when 2 users edit the same file at the same time)? This is a great plugin too!

I've discovered your fork yesterday and I was very happy to see that someone is maintaining and improving Codiad! So thank you for your work!

**Comment by HLSiira** [comment]
Alright, I'll try to see if I can get it working, especially because some of the things you just listed are thing I also have struggled with within Atheos, potentially enough to include a default set of Macros, or integrate it into Atheos by default as well.

Actually the FileUse is built into Atheos by default, it's in the Active component. When you open a file, it checks and whenever you `focus` on a file as well. If someone is working on the same file, it'll warn you. I'm actually considering fully integrating the Collaborative Plugin as a whole into Atheos so that way, if you work on a file with someone else, it's by default seamless.

Thank you! I really appriciate people finding Atheos and seeing the value in it, helps keep me motivated to work on it.

**Comment by tchavot** [comment]
Great news, thank you!

**Comment by HLSiira** [comment]
I have to completely rebuild the context menu system first, but this is a really powerful tool so I'll be merging it into the main source soon.

**Comment by tchavot** [comment]
Hi,
Are you still planning to implement that feature?

**Comment by HLSiira** [comment]
Yeah I have it half built but I had to go rebuild some other components first to support it and just got distracted chasing rabbits.

**Comment by HLSiira** [comment]
Finished off this component last night, pushed it to the development branch, let me know how it works for you and I'll add it to master in about a week.

**Comment by tchavot** [comment]
Wow thank you! I've just tested it, it works really great!
Maybe one thing is missing: it should be interesting to have the result of the command displayed, as the codiad plugin did.

**Comment by HLSiira** [comment]
Added a output panel for larger messages and implemented Macro output to it in the latest push to master, looks pretty nice.

**Comment by freylax** [comment]
Thanks @HLSiira for this beautiful IDE! 
I would just like to use the macro editor. Where is the macro expected to be visible. I saved it but could not discover it. 
Warm Regards, Robert

**Comment by HLSiira** [comment]
@freylax When you right click in the file manager on a file with a matching extension/type, it should be one of the context menu options.

**Comment by tchavot** [comment]
> Added a output panel for larger messages and implemented Macro output to it in the latest push to master, looks pretty nice.

@HLSiira Can you please provide a screenshot for this output panel? It displays really weird on my side... (have to scroll to see it...)

**Comment by HLSiira** [comment]
Like this?

![screenshot](https://user-images.githubusercontent.com/792284/147508053-7e7cba7a-6f03-474c-ac69-8c71f1d75d58.png)

**Comment by tchavot** [comment]
I really don't have that... Maybe the update operation has failed. I'll try a fresh installation.

**Comment by tchavot** [comment]
Just tried... But even with a fresh installation with the latest developement branch commit I still have the issue. The output is written at the botton of the page (after the interface) and I have to scroll down to see it!

**Comment by HLSiira** [comment]
If you email me some login details, I can check out your install and see what's going on. My first guess would be your browser is caching the theme files on the client but that's only a complete guess.
