### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#176]
**Describe the bug**
After applying update procedure described in the README.md, an error occurs when trying to access Atheos:
`Fatal error: Uncaught Exception: The file "public/fonts.min.css" could not be opened for writing. Check if PHP has enough permissions.`
I can see that the project has no public/ directory indeed...

**To Reproduce**
1. Apply the update procedure with last commit
2. Access to Atheos

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: FF
 - Version: 87

**Comment by HLSiira** [comment]
What happens if you make the public directory with the correct permissions?

**Comment by tchavot** [comment]
public directory doesn't exist... do I have to create it?

**Comment by tchavot** [comment]
I've created it and it works :)

**Comment by MohamedElashri** [comment]
I think there is a general permission problem when creating projects in Atheos. I had to create projects directories manually and give the correct permission through ```ssh``` everytime.

**Comment by HLSiira** [comment]
@MohamedElashri Would you be able to add more detail? I've never ran into an issue and am struggling to recreate it.
