### ISSUE TITLE
Feature idea: Projects panel closed by default when only 1 project is set

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#177]
**Is your feature request related to a problem? Please describe.**
I have only one project. Each time I open Atehos I need to close the Projects panel because I don't use it and I need more space for the File Manager panel.

**Describe the solution you'd like**
Projects panel could be closed by default when only one project is set. Another solution could be that the latest state (opened or closed) is saved for next Atheos opening.

**Comment by HLSiira** [comment]
Awesome idea, easy add. Thank you, it'll be in the next push to master.
