### ISSUE TITLE
How do I execute programs on Atheos?

### ISSUE THREAD

**Issue by ZePhant** [Atheos/Atheos#183]
I tried hosting Atheos on Gitpod , with success.
But I'm not sure on how to run programs. Do i need to access a menu or use a keyboard shortcut?
 - Windows 10
 - Chrome
 - Version 90

**Comment by HLSiira** [comment]
Do you mean like to compile and execute a script you're working on?

Atheos doesn't necessarily have that natively. You can install the `terminal` plugin to be able to run things, but typically I use Atheos for WebDevelopment, so I point my browser at my server and will reload the page, or I'll have an SSH client open and execute it through that.

I am working on creating a macro plugin to be able to create custom commands for specific file extensions, but it's taking longer than I'd like to do it correctly, if that makes sense.

Does that answer your question?
