### ISSUE TITLE
Header responsibility

### ISSUE THREAD

**Issue by dododedodonl** [Atheos/Atheos#186]
Headers like [index.php](https://github.com/Atheos/Atheos/blob/e34186fe573047d82cff684dd8f388a85fe84db5/index.php#L13) line 13 are not necessarily the responsibility of atheos, there should at least be an option to disable them.

For example, the reverse proxy I have to deal with, terminates the https connection, and proxy's it to php. This reverse proxy also adds the correct HSTS header, but atheos is adding a second one.

In my opinion there are two possibilities to address this:
- per header configuration in config (and maybe even customization)
- disable setting of all headers

Which one would be preferred?

**Comment by HLSiira** [comment]
I'd lean towards adding a custom setting for each header in the config to allow for a lot more flexibility, but the default should remain as on to help foster a higher degree of security. I can add it in either tonight or in a day or two if that works for you?

Does this cause problems or is it a duplication of compute effort? What kind of reverse proxy set up do you have to contend with?

I hope you don't mind me asking a bunch of questions about it before adding it in, just from a learning perspective. I do agree that it should at least be a setting.

**Comment by dododedodonl** [comment]
I don't mind waiting for a bit for you to add it, no rush! As long as I am able to disable all headers, all possible solutions work for me. Please don't feel obligated to fix it asap, I am already very grateful for you maintaining a project like this and solving a quite hard to solve problem.

In the setup that I am forced to use, I cannot control the reverse proxy (from what I recall it was just a simple nginx reverse proxy). This results in some headers being added two times, with sometimes different settings. Some platforms get confused by the same header twice with different settings, some use the first occurrence, some the last occurrence, resulting in different behavior.

Please feel free to ask any more questions :)

**Comment by HLSiira** [comment]
My git went crazy and I don't know why.

I implemented a config setting, I felt it was the easiest way to add configuration without making a ton of new definitions. Let me know what you think.

**Comment by dododedodonl** [comment]
Yes, this would be perfect!
