### ISSUE TITLE
Atheos is not working in php8.0

### ISSUE THREAD

**Issue by LoganTann** [Atheos/Atheos#193]
**Describe the bug**

When starting the editor, got blank page, server error 500, js error `Uncaught TypeError: atheos.i18n is undefined` both in the console and atheo's logs.

**To Reproduce**

1. Lamp stack PHP8.0, vhost, ubuntu 20.04
2. Downloaded the release zip v4.3.0, unzipped inside a directory where php haves group write permissions
3. Opened the atheos folder, prompted for the first config. Set username, password, timezone as GTM+1 Paris, project as an absolute path (located at something like `../anotherWebsite/` if it were relative )

**Expected behavior**
The editor should show up instead of a blank page.

<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/28659185/126050950-e76a7a06-fc74-4626-b139-d1e723c04840.png)
![image](https://user-images.githubusercontent.com/28659185/126051066-8f3d81d2-f27c-4ee5-8185-7400190c06af.png)

</details>

**Desktop :**
 - OS: Ubuntu 20.04 Server (vps) + Client (me)
 - Browser  : Firefox 88.0

**Additional context**
none

**Comment by LoganTann** [comment]
Using a similar config but by installing it using `git clone https://github.com/Atheos/Atheos.git` instead of the release zip while using a similar config, I have got a different error : `Uncaught TypeError: atheos.active is undefined`

![image](https://user-images.githubusercontent.com/28659185/126051259-42552035-5af1-440a-abe3-9ed9bc92d24a.png)

**Comment by LoganTann** [comment]
hmm... using chrome :
![image](https://user-images.githubusercontent.com/28659185/126051323-77241b93-30a5-4ed3-81e3-cbae2066a1b1.png)

That's very strange, I hope this isn't my network...

**Comment by HLSiira** [comment]
That is very strange, I just pull from the main branch and don't have any errors. Do you have client side caching enabled?

**Comment by LoganTann** [comment]
Hello, I just retried and I have the same error, I still don't know if it's a client side or a server side issue.

Client side caching seems to be enabled, I also tried to disable it in the dev console but the result is the same. 

```
Uncaught TypeError: atheos.active is undefined
    init https://shinprog.kagescan.fr/atheos/modules/keybind.js:69
    <anonymous> https://shinprog.kagescan.fr/atheos/modules/keybind.js:165
    pub https://shinprog.kagescan.fr/atheos/libraries/carbon.js:50
    init https://shinprog.kagescan.fr/atheos/modules/system.js:44
    EventListener.handleEvent* https://shinprog.kagescan.fr/atheos/modules/system.js:74
    <anonymous> https://shinprog.kagescan.fr/atheos/modules/system.js:76
keybind.js:69:4
```
Network tab preview : 

![image](https://user-images.githubusercontent.com/28659185/126065015-91006833-bdc0-4194-bafd-4d2f7b0405ef.png)

I can give you the atheos account if you want to try it in your side.

**Comment by HLSiira** [comment]
Actually yeah, that would be great if you're comfortable doing that. Just send me some account info at `liam@siira.io` and I'll see what's going on. It has to be some sort of version mismatch or leftover from something, but that's just a guess.

**Comment by LoganTann** [comment]
Tried Atheos in my university, I get the same error. This might be a server-side problem. 

> Actually yeah, that would be great if you're comfortable doing that. Just send me some account info at `liam@siira.io` and I'll see what's going on. It has to be some sort of version mismatch or leftover from something, but that's just a guess.

I sent you account infos of both atheos and a php shell server access, so you can investigate about this issue. Thanks in advance !

**Comment by HLSiira** [comment]
Wow, this was an incredibly bizarre issue that I don't think I ever could have caught if not for your help and trust.

You're using PHP8, and I didn't catch that, and even if I did, I wouldn't have known about the incompatibilities caused by the upgrade as the incompatible issues were caused by just random mistakes.

In the Right Sidebar `sb-right.php`, I had been calling the translation feature on the server using a much older format, which was fine on PHP7, but `vsprintf` now only accepts args as arrays, and the old format just so happened to be sending a string. Since the error occured there, everything after the sidebar rendering in the index page wasn't running, so the components were never being sent to the server, causing the missing `i18n` feature. Removing/updating the function call fixed that issue, which was the main issue.

However, I noticed that I started seeing bugs in the console and looking into that found I hadn't created a function within Common statically, which was fine in PHP7, but invalid in PHP8. Again, just a complete typo that once fixed, no more errors.

Everything else seems to be running smoothly and I haven't seen any errors, but you'll have to let me know if you come across anymore, thank you for reaching out, I don't have plans to upgrade my server anytime soon so I wouldn't have caught these on my own for a long time!!!

**Comment by LoganTann** [comment]
Hello, I'm glad you've found the error. Thanks again for taking your time by solving the bugs and for being that reactive, the editor works with the last commit in the dev branch and I can edit the files without problems.

I'm actually not working with php (so I won't use Atheos for some days) but here are some error I've found so far : 

* When downloading the terminal plugin : 
  ```
  Uncaught TypeError: Cannot read property 'html' of undefined
    at Object.settled (modal.js:94)
    at XMLHttpRequest.xhr.onload (echo.js:58)
  ```
* Features like the macro editor or some tabs in the settings don't works and produces this bug :  `echo.js:77 POST https://beta.kagescan.fr/Atheos/dialog.php 500 (Internal Server Error)`
* This is the same error when I want to create a new file : there is the window border but no content (and not able to create it) : 
![beta kagescan fr_Atheos_ (1)](https://user-images.githubusercontent.com/28659185/126795424-d1624f30-4031-41e9-bf96-3a991a29c6e5.png)
* When closing the terminal multiple times, I can't open it again (there is the message `overlay click` but no window opens)
* For the first command in the terminal, the current directory is wrong and there is no space between the command and the `$` : 
  ![beta kagescan fr_Atheos_](https://user-images.githubusercontent.com/28659185/126794953-2806553e-6f67-4354-9e2e-126a9fbbb3aa.png)
* This does not occurs when typing no commands. By closing and opening the terminal, the cursor is also strange (`â-` instead of a rectangle) :  
  ![beta kagescan fr_Atheos_ (2)](https://user-images.githubusercontent.com/28659185/126795737-c7ce38b2-0edd-4f05-846e-7e90234dbc41.png)
* Clicking in the project button will close the terminal if opened
*  `Last Login: DateTime`

**Comment by HLSiira** [comment]
I just pulled a large number of bug fixes into master and some of them are direct references to the bugs you noted, would you mind posting a new message based on the recent update?

**Comment by martadinata666** [comment]
#### Describe the bug

Session error, and i8n error

#### To Reproduce

   1. PHP fpm v8
   2. git clone from dev branch
   3. nginx front

#### Expected behavior
Should show the homepage like php 7.4 

#### Desktop :

    OS: Debian Sid
    Browser : Firefox 90

#### Additional context
Error log

```
Deprecated: Required parameter $path follows optional parameter $table in /var/www/html/traits/database.php on line 33

Warning: session_name(): Session name cannot be changed after headers have already been sent in /var/www/html/common.php on line 101

Warning: session_start(): Session cannot be started after headers have already been sent in /var/www/html/common.php on line 102

Warning: Undefined variable $_SESSION in /var/www/html/traits/helpers.php on line 66

Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /var/www/html/traits/helpers.php:66 Stack trace: #0 /var/www/html/common.php(152): Common::data('SESSION', 'lang', NULL) #1 /var/www/html/traits/i18n.php(181): SESSION('lang') #2 /var/www/html/traits/i18n.php(84): i18n->getUserLangs() #3 /var/www/html/common.php(107): i18n->init() #4 /var/www/html/common.php(136): Common::startSession() #5 /var/www/html/index.php(13): require_once('/var/www/html/c...') #6 {main} thrown in /var/www/html/traits/helpers.php on line 66
```
