### ISSUE TITLE
Can't select setting tabs

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#196]
**Describe the bug**
When clicking on a settings tab (System, Codegit, Draft, etc) it doesn't open the choosen section (it stays on the Editor section)

**To Reproduce**
1. Click on Settings
2. Click on CodeGit

**Expected behavior**
The shown section should change

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Firefox

**Comment by tchavot** [comment]
Have now more details: it works when deleting the minimap plugin!

When adding the minimap plugin the following error is raised:
Uncaught TypeError: oX(...) is undefined
    init xxx/public/plugins.min.js:12
    <anonymous> xxx/public/plugins.min.js:12
    pub xxx/public/libraries.min.js:12
    init xxx/public/modules.min.js:12

**Comment by HLSiira** [comment]
Should be fixed and pushed to the latest MiniMap plugin repository, thank you for letting me know.

Please feel free to let me know if you run into any further bugs
