### ISSUE TITLE
Analytics setting is not correctly saved

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#197]
**Describe the bug**
I have set "disabled" to the analytics setting in the installation panel. But now when I go to the settings I can see that the analytics setting is set to "enabled". If I change it to "disabled", then refresh the page and go again to the settings panel, it still shows "enabled" !

**Comment by HLSiira** [comment]
Hey thank you for letting me know, PHP has some annoying traits that compounded into this just being a huge annoyance. Let me know if the fix works for you or if you still notice some off behavior.
