### ISSUE TITLE
Avoid automatic replacements in editor

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#201]
Is it possible to disable these automatic replacements in text editor ?
For example !=, >=, etc
![2021-07-29 16_55_18-Atheos IDE](https://user-images.githubusercontent.com/3533283/127515246-9681f74c-8632-4337-b700-2c8e8deb2552.png)
![2021-07-29 16_54_50-Atheos IDE](https://user-images.githubusercontent.com/3533283/127515253-a0c73d7f-c720-4606-9346-b9fc0603b2d2.png)
![2021-07-29 16_54_22-Atheos IDE](https://user-images.githubusercontent.com/3533283/127515254-b9ff3614-6582-4898-8b7e-4ba7ea9089b1.png)

**Comment by HLSiira** [comment]
Not really, they're built into the font files. They aren't replacements for the actual characters, just the way the font renders on the screen. I could try to implement the ability to disable them or switch font files but I'd have to think about how to do that per user or just as a global setting.

They're called Ligatures and are pretty popular nowadays in coding: [Read More Here](https://betterwebtype.com/articles/2020/02/13/5-monospaced-fonts-with-cool-coding-ligatures/)

**Comment by tchavot** [comment]
Ok I understand. I’ll try to get used to it.
Maybe it could be interesting to have the possibility to choose the font
(either to disable ligatures or to simply personalize the editor as you
already do with color themes).

Le jeu. 29 juil. 2021 à 18:25, Liam Siira ***@***.***> a
écrit :

**Comment by tchavot** [comment]
Thanks for your commit but I can't find the option in the Editor Settings panel... Maybe I'm not in the right place?
![image](https://user-images.githubusercontent.com/3533283/140766683-6891b209-51be-4edf-99fa-a4418ed5094e.png)
