### ISSUE TITLE
Tabs drag n drop doesn't work properly

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#202]
**Describe the bug**
Dragging and dropping tabs creates many display bugs as you can see an example below (cursor has been released):
![2021-08-17 17_27_34-Atheos IDE](https://user-images.githubusercontent.com/3533283/129755559-a2abad1d-d888-499e-884f-e4909863d921.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 78.10.0

**Comment by HLSiira** [comment]
Looks like it's not removing the ghost tab used for the drag/drop mechanism, I'll dig around and see what I can find. It happens in the file manager as well and I haven't figured out why. 

Thank you for letting me know, I'll try to fix it as soon as I can, although I'm swamped in other projects, so I hope you don't mind me taking a little bit of time.

**Comment by tchavot** [comment]
Hey @HLSiira it seems that it broke the drag n drop behavior in the file manager...
Can't drag n drop a file in a directory!
Browser: Firefox.

**Comment by HLSiira** [comment]
Merp. I thought I'd try to head that off and fix that issue, I'll look into and see what shows up. Have you run into any other issues on FX?

**Comment by tchavot** [comment]
For now I can see no more issues with FF.
But please note that the issue mentioned here concerns both Firefox and Safari!

**Comment by HLSiira** [comment]
@tchavot I've built a server using PHP8 just to verify and can't reproduce this bug on any browser. Please let me know if there are any error messages, update any caches and use the most recent push to dev if possible. Any information is appreciated!

**Comment by tchavot** [comment]
Okay I get it. I tried to drop a file on a folder name and it doesn't work. But if I open the folder first and then I drop the file amidst the folder content, then it works! Thanks.

**Comment by HLSiira** [comment]
Yeah I've trying to figure out a way to make it so that will happen more naturally, but I'm not creative enough to think of a nice way to set it up with making stuff really complicated. It irritates me.

**Comment by 3642066** [comment]
That bug happens on codiad since when codiad was........ it called ...

**Comment by HLSiira** [comment]
Problem is that almost none of the source is Codiad anymore. Heck, I don't think the Drag and Drop feature from Codaid was actually Codiad, IIRC it used a jQuery plugin. Atheos is almost all in house coded except for the Ace Editor I think.
