### ISSUE TITLE
Cannot find a way to reset original admin username and password

### ISSUE THREAD

**Issue by inglesuniversal** [Atheos/Atheos#205]
I can't find a way to update this data.

Either I forgot my original password or something happened along the way

How to reset password or create an option to reset it.

**Comment by HLSiira** [comment]
Hey, Sorry for the delayed reply. I'll have to think about this one for a while to think of an intuitive way to reset the admin user/pass but if you delete your data folder, or just copy it over somewhere else, it should guide you through the "reinstall" process and handle it for you.

The only thing I can think of is to have PHP generate a password again somehow and manually edit the `data/users.json` file but that seems excessive

**Comment by inglesuniversal** [comment]
Thanks for your time giving me some pointers on how to solve this in the mean time. I'll follow the steps and I'll make sure to keep the new credentials in a safe place... LOL

Great project by the way, you brought back to life CODIAD in a more modern and sophisticated way.

**Comment by inglesuniversal** [comment]
Hi, I was able to re-install your Awesome and Updated script without any Issues... I had to "clone" de config.php file from a previous installation of CODIAD, since your folder or project did not come with it, or at least I couldn't find it.

Thanks and hope you can find an easier way to reset admin password if ever lost or compromised.

Regards
