### ISSUE TITLE
Not working settings font size

### ISSUE THREAD

**Issue by edichome** [Atheos/Atheos#208]
Hello, in the settings popup left menu not clickable links: Editor, System, Drafts.
When open Settings and as default Editor tab - have not font size options.
Server Apache Debian 10 PHP8.0
Browser  Chrome
<img width="782" alt="Screen Shot 2021-10-31 at 10 49 48" src="https://user-images.githubusercontent.com/5670645/139564781-4cf0a68a-3b79-461e-8d4b-4917b95fde85.png">

**Comment by HLSiira** [comment]
Are you getting any errors in the apache error log?

**Comment by HLSiira** [comment]
I can't replicate this bug, set up a fresh install on PHP8. With out more information, I'll have to close this issue, let me know if there is more to it.
