### ISSUE TITLE
Access documents outside workspace dir - Not sure if this is a bug?

### ISSUE THREAD

**Issue by pedroponte** [Atheos/Atheos#212]
**Describe the bug**
I'm trying to set up a project based on absolute path, not sure if it is atheos or my nginx server preventing me from creating a project outside the workspace dir.
Any hints please?

**To Reproduce**
Create new project, provide absolute path outside workspace

**Expected behavior**
A project is created and files acessed outside workspace

**Desktop (please complete the following information):**
 - Mac OS
 - Brave browser
 - v5

**Additional context**
I have tried with symbolic links and direct folder access.
The user has access to the folder and sym link via the terminal.

**Comment by HLSiira** [comment]
That's strange, I almost completely set absolute paths outside of the workspace. When you say "The user has access", do you mean the web user? On a typical apache installation, that's going to be "www-data".
