### ISSUE TITLE
Bulk account creation

### ISSUE THREAD

**Issue by HLSiira** [Atheos/Atheos#213]
**Is your feature request related to a problem? Please describe.**
Creating bulk users is time consuming, would be nice to be able to import or mass create users.

**Describe the solution you'd like**
A CSV template for importing users would be handy

**Additional context**
Suggested by @Shahi-Paneer

**Comment by mclindy** [comment]
This is great. Thanks!

I would like to add to this ability. I'd like to be able to assign a value to the userACL property, probably within the create method in /components/user/class.user.php

Can anyone point me to the file(s) that handle the CSV file upload? I don't see mention of it in /components/user/README.md 

Perhaps I can edit a method within _that_ file and I won't need to edit class.user.php

Thanks in advance,
Greg.

**Comment by Shahi-Paneer** [comment]
> This is great. Thanks!
> 
> 
> 
> I would like to add to this ability. I'd like to be able to assign a value to the userACL property, probably within the create method in /components/user/class.user.php
> 
> 
> 
> Can anyone point me to the file(s) that handle the CSV file upload? I don't see mention of it in /components/user/README.md 
> 
> 
> 
> Perhaps I can edit a method within _that_ file and I won't need to edit class.user.php
> 
> 
> 
> Thanks in advance,
> 
> Greg.

Looks like it's components/user/init.js around line 230

**Comment by mclindy** [comment]
Thank you. Yes, I see it. I will mess around and report back.
