### ISSUE TITLE
Atheos error terminal Plugin

### ISSUE THREAD

**Issue by CremiOfficial** [Atheos/Atheos#216]
Hi, I get the problem with Plugin Terminal. I write easy command("cd, echo, ls"), and terminal write me text "Array" error problem:
PHP Notice:  Undefined index: project in /root/Atheos/plugins/Terminal/terminal.php on line 40
[Wed Dec 22 13:45:31 2021] PHP Notice:  Undefined index: project in /root/Atheos/plugins/Terminal/terminal.php on line 40
[Wed Dec 22 13:45:31 2021] PHP Notice:  Undefined index: project in /root/Atheos/plugins/Terminal/terminal.php on line 48
[Wed Dec 22 13:45:31 2021] PHP Notice:  Undefined index: project in /root/Atheos/plugins/Terminal/terminal.php on line 113
[Wed Dec 22 13:45:31 2021] PHP Notice:  Array to string conversion in /root/Atheos/plugins/Terminal/terminal.php on line 142

**Comment by tchavot** [comment]
Same issue here. Terminal plugin always answer "Array" regardless the command I write.

**Comment by CremiOfficial** [comment]
> Same issue here. Terminal plugin always answer "Array" regardless the command I write.

+

**Comment by HLSiira** [comment]
Hey, I recently pushed an update to the Terminal Plugin that's supposed to correct this issues, are you all still running into this with the most recent version?
