### ISSUE TITLE
Line Wrap setting not used when login

### ISSUE THREAD

**Issue by tchavot** [Atheos/Atheos#217]
**Describe the bug**
When I login to Atheos the Line Wrap setting (which is set to true) is not used. Lines are not wrapped. Then I have to go to the settings panel, click on the True button for the Line Wrap setting, and the setting is now used. When I refresh the Atheos tab the setting is still used. But when I logout and then login again, I have to redo the whol thing.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox

**Comment by HLSiira** [comment]
Fixed this in a most recent push to the dev branch, but accidentally referenced the wrong issue number, this should be fixed now.
