### ISSUE TITLE
Can't get it working on shared hosting

### ISSUE THREAD

**Issue by andrewx345** [Atheos/Atheos#221]
It's Atheos working on Shared hosting? I can't get it done... I can complete the setup without issues, but after that, the page remains blank like this: 
![image](https://user-images.githubusercontent.com/84435046/157244137-2b54c727-2934-4558-a88e-04020fc23410.png)
Even if I press on buttons, they do nothing...

**Comment by HLSiira** [comment]
Sorry for the delay on this, never saw the notification for it. Are you still seeing this? What kind of errors are you seeing both on the server or in the browser?
