### ISSUE TITLE
can't create files in projects

### ISSUE THREAD

**Issue by tegger2000** [Atheos/Atheos#227]
Hello,
I have started Atheros with a fresh installation via git clone and created a project. So far everything works. Now when I want to create a new file, it does not work.

I got the error on apache error_log

`[Thu Apr 28 11:11:25.765349 2022] [php7:error] [pid 18009] [client 1.1.1.1:58090] PHP Fatal error:  Uncaught ErrorException: fopen(tragra/index.php): failed to open stream: No such file or directory in /var/www/html/Atheos/components/filemanager/class.filemanager.php:37\nStack trace:\n#0 [internal function]: {closure}(2, 'fopen(tragra/in...', '/var/www/html/A...', 37, Array)\n#1 /var/www/html/Atheos/components/filemanager/class.filemanager.php(37): fopen('tragra/index.ph...', 'w')\n#2 /var/www/html/Atheos/components/filemanager/controller.php(42): Filemanager->create('tragra/index.ph...', 'file')\n#3 /var/www/html/Atheos/controller.php(41): require('/var/www/html/A...')\n#4 {main}\n  thrown in /var/www/html/Atheos/components/filemanager/class.filemanager.php on line 37`

PHP 7.4.19
Apache 2.4.53 
installed in a subdirectory like http://xxx.company.comp.org/Atheos

when i manually create a file in workspace/tragra and tried the preview i got a wrong url 
 without "Atheos" http://xxx.company.comp.org/workspace/gratra/index.php.

**Comment by giangduong** [comment]
Still get this error. Already run this command: chown apache:apache -R /var/www/html/
