### ISSUE TITLE
File actions doesn't work

### ISSUE THREAD

**Issue by norby004** [Atheos/Atheos#229]
Hello everyone!

I'm noticed a pretty big problem.
I'm tried to open files, but not working and i'm started watching the code.

**There is a problem with the paths.**

Example code:

Open the file function
/components/filemanager/class.filemanager.php:300

Added to the beggining of the function:

```
$path = Common::cleanPath($path);
$relativePath = $path !== "/" ? "$path/" : $path;
$path = Common::isAbsPath($path) ? $path : WORKSPACE . "/" . $path;
```

The other functions are not good either. (rename, duplicate, create, etc...)

Is it just a problem with me or isn't something good with the installation?

Environment:
Apache
PHP 7.3
Ubuntu 18.04
Subdomain installed in root dir.

I'm waiting for your feedback. Thanks.

**Comment by donmortis** [comment]
+1

I installed subdomain root directory, and not working, create, modify, delete, move etc. I check @norby004 message and look biggest bug. Switch maybe previous version, and i waiting new pull request. Have nice day!

**Comment by HLSiira** [comment]
Hey, sorry Atheos is misbehaving on you both like this. I'm unable to take a look at this right now, but I'll try to look later today or tomorrow.

My first instinct is that your PHP versions might be out of date, there are some functions that changed how they operate in the engine from PHP 7.3 to 7.4.

I'm also curious if the web user `www-data` has read/write permissions in the project folder.

**Comment by donmortis** [comment]
@HLSiira Yes. Recursive chown try www-data and next time 777 chown, neither works... 

I don't think a php version would be the problem because error messaging is turned on. It does not throw a deprecated error.

After adding the said 3 lines to each function, the functions work, after that it only sends an error for continuous ajax requests, which does not affect the operation.

**Comment by donmortis** [comment]
@HLSiira 

I checkd PHP 7.4.x, not working and checkd errors PHP 7.3 (enabled ini_set E_ALL and on display), not throw error!

Problem, not the PHP 7.3.

**Comment by norby004** [comment]
I have also tested on PHP 7.4.3 and didn't work for me with file action. (open, rename, duplicate, etc...)

**Comment by HLSiira** [comment]
Can one of you email me some login details so I can see your installs? Sadly I'm not able to replicate any of these issues on my own hardware.

**Comment by norby004** [comment]
> Can one of you email me some login details so I can see your installs? Sadly I'm not able to replicate any of these issues on my own hardware.

Which version are you testing?

I'm installed on main branch. You too or latest tagged release?

**Comment by donmortis** [comment]
@HLSiira 

You try clean install main branch? NOT 5.0 release.

**Comment by norby004** [comment]
> Can one of you email me some login details so I can see your installs? Sadly I'm not able to replicate any of these issues on my own hardware.

**Comment by HLSiira** [comment]
@norby004 I'm the main dev of Atheos, I'm only ever on the main branch of Atheos.

I think I just fixed the bug in the most recent push to the dev branch, I didn't realize the bug had to do with a project within the workspace.

**Comment by donmortis** [comment]
@HLSiira I try developer branch and the problem is not gone :(

Try clean install and check bug.

Can a PHP module be needed that is not described in the documentation and needs to be installed?

**Comment by HLSiira** [comment]
Unfortunately I can't say. It would show up in the logs and sadly I can't recreate the issue on my server. I'll keep playing with it to see if I can figure it the cause but I'm not sure where to look for the problem.

**Comment by ApplySci** [comment]
I've reproduced norby004's problem - and solution - on a fresh install

**Comment by ApplySci** [comment]
>  I'll keep playing with it to see if I can figure it the cause but I'm not sure where to look for the problem.

well the index function in `components/filemanager/class.filemanager.php` works just fine. It's the other functions that have the problem.

The index function has:
```
$path = Common::cleanPath($path);
$relativePath = $path !== "/" ? "$path/" : $path;
$path = Common::isAbsPath($path) ? $path : WORKSPACE . "/" . $path;
```
at the start of it. The other functions in that CLASS don't. By adding those three lines to the start of the other functions, they all work.

**Comment by haexperts2020** [comment]
Fresh install of Ubuntu 22.04 and PHP 8.1.2

Had the same error. Was trying to just create a test.php file in the main workspace. Here it is: 

```
PHP Fatal error:  Uncaught ErrorException: fopen(main/test.php): Failed to open stream: No such file or directory in /var/www/jw/public/atheos/components/filemanager/class.filemanager.php:37\nStack trace:\n#0 [internal function]: {closure}()\n#1 /var/www/jw/public/atheos/components/filemanager/class.filemanager.php(37): fopen()\n#2 /var/www/jw/public/atheos/components/filemanager/controller.php(41): Filemanager->create()\n#3 /var/www/jw/public/atheos/controller.php(41): require('...')\n#4 {main}\n  thrown in /var/www/jw/public/atheos/components/filemanager/class.filemanager.php on line 37
```

Added this to all the functions except the index function and all is good. Thanks 

```
$path = Common::cleanPath($path);
$relativePath = $path !== "/" ? "$path/" : $path;
$path = Common::isAbsPath($path) ? $path : WORKSPACE . "/" . $path;
```
