### ISSUE TITLE
I can replace Codiad by Atheos?

### ISSUE THREAD

**Issue by MythodeaLoL** [Atheos/Atheos#232]
I'm using Codiad, with easyphp, i can replace filesof Codiad with Atheos without problems? If i need to change someting, please help.

Thank you.

**Comment by HLSiira** [comment]
It's better to do a fresh install of Atheos rather than overwrite Codiad with Atheos. The structures are so wildly different at this point that they're almost completely unrelated and you'll most likely run into bugs by doing that
