### ISSUE TITLE
Can we use Atheos with PHP8?

### ISSUE THREAD

**Issue by kaisoft** [Atheos/Atheos#234]
I using Atheos already and it's useful run very fine in PHP7, Thankyou verymuch to all of project creators, and I have plans to upgrade to PHP8 soon , I test Atheos with PHP8 and found these error message occrur from some PHP function deprecate, and Atheos show the frame and halt with blank screen , so I keep these error log to ask , How to fixed them?.

[05-Jun-2022 20:19:50 Asia/Bangkok] PHP Deprecated:  
Required parameter $minifiedFileName follows optional parameter $type in ./atheos/traits/cls.source.php on line 119

[05-Jun-2022 20:19:50 Asia/Bangkok] PHP Deprecated:  
Required parameter $files follows optional parameter $type in ./atheos/traits/cls.source.php on line 119

[05-Jun-2022 20:19:50 Asia/Bangkok] PHP Deprecated:  
Required parameter $path follows optional parameter $type in ./atheos/traits/cls.source.php on line 164

[05-Jun-2022 20:19:50 Asia/Bangkok] PHP Fatal error:  Uncaught 
TypeError: vsprintf(): Argument #2 ($values) must be of type array, string given in ./atheos/traits/i18n.php:168

Stack trace:
#0 ./atheos/traits/i18n.php(168): vsprintf()
#1 ./atheos/common.php(140): i18n->translate()
#2 ./atheos/components/sidebars/sb-right.php(54): i18n()
#3 ./atheos/index.php(104): require_once('/share/CACHEDEV...')
#4 {main} thrown in ./atheos/traits/i18n.php on line 168

**Comment by HLSiira** [comment]
Hey, yes it should run on PHP8, have tested it a few times myself and I think I worked out most of the bugs. Are you running the latest push to `main` or are you using the latest release?

**Comment by kaisoft** [comment]
Thanks for the answer And sorry for I didn't see that there was have an updated already / for infomations the version I used is 5.0.0 (get from the folder) and files timestamp are 7/17/2021 / and now , I saw the new update file. and I'll download it and try it and after that i will let you know the results sir.

**Comment by kaisoft** [comment]
I'm back sir. , first of all I try to extract files to replace old and run it , it's show editor frame and blank screen , may be it's occur from wrong way, so i delete all old files in folder and extract the new one to re-install but still have error with this below message sir. 

[05-Jun-2022 23:30:28 Asia/Bangkok] PHP Fatal error:  Uncaught 
TypeError: array_key_exists(): Argument #2 ($array) must be of type array, bool given in ./atheos/traits/checks.php:22
Stack trace:
#0 ./atheos/components/sidebars/sb-left.php(41): Common::checkAccess()
#1 ./atheos/index.php(71): require_once('components/sidebars/sb-left.php')
#2 {main}
  thrown in ./atheos/traits/checks.php on line 22

**Comment by kaisoft** [comment]
I test version main with PHP Version 7.4.20 too and this is result. if you need.
I found some thing difference from version released 18 Jul 2021 (a) and atheos-main (b)
1. back ground on login screen (a) look greate and (b) i cann't see logo it's so dark and never show background too.
2. after install (with username,password) i can't sign in (i surely to don't make wrong typing).

**Comment by HLSiira** [comment]
Did you refresh your browser cache of the client side assets post install of the latest version?

**Comment by HLSiira** [comment]
@Torsten-K Are you pulling from the main branch or the latest release?
Latest releases haven't been update in a while.

**Comment by Torsten-K** [comment]
@HLSiira Oh, latest release, I guess. I will try the main branch and report again. Thanks for your quick answer.

**Comment by Torsten-K** [comment]
I can confirm now that Atheos from the main branch works with PHP 8.0 and also 8.1. Thanks for your help! But … can I buy you coffees via PayPal instead of credit card (as I don’t have one)?

**Comment by HLSiira** [comment]
Lol I actually don't know. You don't have to, but I won't say no. Is there something I should do on my end? 

Thank you for confirming, I was really starting to think that I was giving off "works on my machine" vibes.

**Comment by Torsten-K** [comment]
> Is there something I should do on my end?
No, I found your email address on your profile page. But do you use PayPal anyway? If you do, is the email address the one you also use for PayPal? Just to make sure that the amount will arrive correctly.

**Comment by haexperts2020** [comment]
I confirm this works well with PHP 8. I needed to clear cache tho.
