### ISSUE TITLE
Normal users cannot change their password

### ISSUE THREAD

**Issue by giangduong** [Atheos/Atheos#237]
**Describe the bug**
Normal users cannot change their password

**Screenshots**

<img width="1374" alt="image" src="https://user-images.githubusercontent.com/8393739/176424979-fd10b0f3-bbb0-47a2-945d-4ba867fe8b35.png">

**Desktop (please complete the following information):**
 - OS: Centos 7
 - Browser safari
 - Atheos version 5.0
 - Php 7.4
 - Apache 2.4

**Additional context**

**Comment by HLSiira** [comment]
Can you confirm if this is still an issue on the most recent push to main? It's been so long since I touched this and I think I fixed it at some point.
