### ISSUE TITLE
Beautify  - Expand option for Brace not working

### ISSUE THREAD

**Issue by indyanafr** [Atheos/Atheos#239]
Hi all,
I'm trying to use Atheos with beautify. I have an issue with the brace option. I change the default setting in plugins/Beautify/init.js with 
the option brace_style: "collapse" changed to brace_style: "expand".

That's should put the brace on a new line instead of have it on the control statement's line, but option does'nt work.

There is any other setting in Atheos that override the beautify option file?

Thanks for your help.

**Comment by HLSiira** [comment]
Can you send me screenshots of what you're trying to accomplish?

**Comment by indyanafr** [comment]
Hi!
The first screenshot is the actual result of code beautifier with the "collapse" mode, the brace is on the control statement :
![image](https://user-images.githubusercontent.com/5808043/187086930-6247a714-2a0c-43fb-8d43-77039f69ffb4.png)

Here is the result that i should have with "expand" mode, the brace have is own line : 
![image](https://user-images.githubusercontent.com/5808043/187086956-e1041e74-74dd-4538-8db3-076b451afe55.png)

**Comment by indyanafr** [comment]
In my memories, this option worked perfectly with Codiad

**Comment by HLSiira** [comment]
Please reinstall the plugin from the repo and let me know. I added a settings box within the IDE itself to change the Brace Style. Make sure you clear your browser cache, as changing the default setting within the `init.js` file as you did should have changed the default mechanism so I can only guess that your browser wasn't grabbing the new files.

Let me know if it works as I didn't have a lot of time to play with it myself.

**Comment by indyanafr** [comment]
Well, the setting box appear and seems saved correctly, but the Beautify init.js was not changed (i don't know if it's normal or not).
I login/logout several times with clear of the browser cache each time.... but with no results, the Beautify behavior is still the same, 

Perhaps a bug from Beautify script, so, i will have to learn to work with the new brace style!... 

Anyway, thanks for your help!
