### ISSUE TITLE
CodeGit doesn´t work

### ISSUE THREAD

**Issue by MartinKolb1987** [Atheos/Atheos#242]
Hi Liam,
first of all, thank you for this really awesome cloud IDE.
Unfortunately, I can't get the CodeGit to work properly (tried quite a few things). Pull/Fetch works wonderfully, only push doesn't work. Is there anything to consider here? Does this work for you without problems and if so, how exactly do you proceed here? Thanks a lot for your help! Best regards Martin

**Comment by HLSiira** [comment]
Hey, I actually noticed this on my end a few weeks ago but figured something else had broken and didn't have time to work on it lol

It looks like Git increased some default security measures and it causes problems with key storage, so I'm going to have to readdress how I currently handle it, but if you set it up like me, you might want to check out the permissions for the keys your using, basically run `sudo -u www-data git push origin <<BRANCH>>` and you'll see what I'm running into, IF you have your system set up like I do.

However to really fix it, I need to clean up the code git component, which is a major component so this might take me some time to delve into.

**Comment by MartinKolb1987** [comment]
Hi Liam,
I debugged your code and added a vardump in the "components/codegit/traits/execute.php". As result I get "fatal: could not read username for 'gitlab'....". Probably you would have to store a username/password combination for the "push". Maybe you can add that faster, since you know the code better. What kind of error do you get?
Best regards
Martin

<img width="660" alt="Bildschirmfoto 2022-10-16 um 08 47 32" src="https://user-images.githubusercontent.com/1842716/196022557-f934a54c-e387-4203-8ff1-daf97b275268.png">

**Comment by HLSiira** [comment]
Mine is to do with how my SSH keys are stored, so very different errors. I'll look into this one though to see what the deal is, my first goal is to make the error output more available to the user. For some reason, the moron who wrote it originally (me) decided to drop the error reporting in favor or a simple fail/pass system.

My first thought is that you don't have your username configured on your git system or within Atheos itself, but not 100% certain about that. It's been a decent amount of time since I worked in the CodeGit component so I'm having to relearn how I built it, but it's coming back to me fairly quick. I do think the error you're running into seems a lot easier to fix than what I originally thought this was going to be.

**Comment by MartinKolb1987** [comment]
Better error output would be nice :-) . I have stored the username in Atheos Editor. Both "global" and "project-related". The question is whether you can not simply store a username/password (without SSH keys etc.)?But I don't know how complex that is. In any case, it's very cool that you're looking at this again.Am 16.10.2022 um 21:25 schrieb Liam Siira ***@***.***>:﻿
Mine is to do with how my SSH keys are stored, so very different errors. I'll look into this one though to see what the deal is, my first goal is to make the error output more available to the user. For some reason, the moron who wrote it originally (me) decided to drop the error reporting in favor or a simple fail/pass system.
My first thought is that you don't have your username configured on your git system or within Atheos itself, but not 100% certain about that. It's been a decent amount of time since I worked in the CodeGit component so I'm having to relearn how I built it, but it's coming back to me fairly quick. I do think the error you're running into seems a lot easier to fix than what I originally thought this was going to be.

**Comment by mach7** [comment]
I've been able to get my system working with CodeGit by installing Github CLI and then authenticating with that. Since doing that I'm able to utilize CodeGit 100%
