### ISSUE TITLE
No more git status (and other problems)

### ISSUE THREAD

**Issue by coca348** [Atheos/Atheos#257]
**Describe the bug**
Hey Liam, your last pull request (from develop branch)  #256  introduce some big problems.
No more git status and an error 500...
First...
PHP Parse error:  syntax error, unexpected identifier "debug", expecting "function" or "const" in /var/www/html/atheos/components/codegit/traits/execute.php on line 23
Because of the deletion of "	private function parseCommandCodes($code) {"
But there is other problems...
I check and tell you !

**To Reproduce**
1) Install last version
2) Connect
3) Watch for the git status

**Expected behavior**
Well, you know... ;-)

**Comment by HLSiira** [comment]
Yeah, rebuilding Codegit and merging branches together broke some (a lot) things. My last push should have fixed a lot of it on the development branch IIRC, but I still have to test it all out. Codegit is a huge PITA.

**Comment by coca348** [comment]
Ok, so i revert last commit on my install and i wait until the new code is ready ! Thanks

**Comment by HLSiira** [comment]
Should be fixed with the latest pushes to development, I'll give it a few days to see if I notice anything and then merge into Main

**Comment by HLSiira** [comment]
@coca348 @mclindy Pushed some fixes to the development branch, can either of you check to see if your issues have been fixed?

**Comment by mclindy** [comment]
Git pull with 4 files changed, 13 insertions, 9 deletions.
Problem with creating new project with absolute path has been resolved. Wow, thanks for the quick turn-around. Above and beyond!
