### ISSUE TITLE
Git not function anymore

### ISSUE THREAD

**Issue by superkekko** [Atheos/Atheos#266]
I've just downloaded the main branch and git extension is not function anymore.

There are tons of 500 errors of the "controller.php"

![immagine](https://user-images.githubusercontent.com/25342565/226587889-5c02e6eb-45b1-45af-99d8-6761f521dd6f.png)

![immagine](https://user-images.githubusercontent.com/25342565/226588282-723f326e-e552-4b2a-9859-49f740eb0daa.png)

This is the stack trace
![immagine](https://user-images.githubusercontent.com/25342565/226588885-3a60cf95-b871-44d2-b920-db97c7362acf.png)

The error is in this commits because the previous version is working
![immagine](https://user-images.githubusercontent.com/25342565/226598116-851a5d7f-93bf-451a-ba40-50a2c68f7692.png)

**Comment by HLSiira** [comment]
Duplicate issue #242
