### ISSUE TITLE
Cannot open files from the file manager.

### ISSUE THREAD

**Issue by N0tACyb0rg** [Atheos/Atheos#268]
**Describe the bug**
Using the official docker image (plus JDK 11), I cannot open any files from a cloned project from the file manager. However, searching for content inside the file and opening that line opens the file (I can also open files from the Atheos source code). The project was cloned using Atheos's UI.

**To Reproduce**
1. Go to the file manager
2. Open a cloned project.
3. Left-click on any file.

**Expected behavior**
Left-clicking on a file opens it.

**Desktop**
-
**Client**
 - OS: ChromeOS
 - Browser: Chrome
 - Version: 111.0.5563.100

**Server**
- OS: Ubuntu 22.04.2 LTS
- Docker version: 20.10.16

**Comment by HLSiira** [comment]
Try pulling it now, I just rebuilt the docker image with the latest build, so here's hoping. My docker game is fairly weak

**Comment by N0tACyb0rg** [comment]
Could you add/provide your up-to-date Dockerfile? I'm writing a quick Action to build the image automatically.

**Comment by HLSiira** [comment]
https://github.com/Atheos/Atheos-Docker
