### ISSUE TITLE
Can't log in error 500 on controller.php

### ISSUE THREAD

**Issue by poVoq** [Atheos/Atheos#274]
I tried installing Atheos (by cloning this git repo) with nginx behind a tls terminating reverse-proxy and installation and everything seems to have gone fine with the config.php and the project directories being created correctly.

But when I try to log in it just fails with a very shortly visible "Message undefined" error shown in the top left.

The browser console shows an error 500 on the controller.php but no other error messages (nice Atheos ascii art there btw).

Server logs do not seem to show anything either as far as I can tell, but maybe I am looking at the wrong place.

I have another php-fpm app working with similar settings so I assume my server is working correctly.

Anything I could do to further investigate what is going wrong?

Thanks!

**Comment by HLSiira** [comment]
Sadly I don't have a lot of experience with nginx aside from  a slightly similar setup for a different app. My first throught would be to check file permissions, and then maybe looking at the data directory to see if everything looks right.

If it installed correctly, I can only assume that a recent push to main has caused something to get weird and potentially your user data file isn't right for some unknown reason.

Message undefined with 500 tells me that it would have to be some sort of syntax or parsing error.

I'm surprised you don't have anything in your logs, a 500 error is typically a big deal and should be recorded somewhere

**Comment by poVoq** [comment]
Thanks for the quick reply. It looks all correct in the user data folder to me, but I am not 100% sure.

I will try to find where exactly it might be logging stuff. I only recently switched from Debian to Fedora and the logging infra is somewhat different there and I feel a bit lost in the logs to be honest ;)

Maybe I should first try the last October 2022 release version and see if it might be a recent regression?

**Comment by HLSiira** [comment]
You could, not a bad idea as it would eliminate some stuff. Hopefully it's not annoying to do so.

What made you switch? Just trying something new?

**Comment by poVoq** [comment]
Same issue with the October 2022 release files.

As for Fedora: more up to date packages while still very stable and better Podman integration.

**Comment by poVoq** [comment]
Huh, ok seems like I solved it. For some reason Fedora really likes to have all the php stuff configured for Apache only.

Changing the group ownership of `/var/lib/php/session` folder to `nginx` from the original `apache`  allows me to log in :)

**Comment by HLSiira** [comment]
Glad you solved it, it looks like a real head scratcher. Can you write more details about this error?

It looks like you're saying that Fedora configured all the php folders with apache as a default owner, but not nginx, so it couldn't run any of the code until you added nginx to the group?

**Comment by poVoq** [comment]
Yes, contrary to Debian and the likes, where there is the shared "www-data" user that works for both Apache2 and Nginx, Fedora has separate "apache" and "nginx" users and all the advanced php stuff is by default only configured for "apache".

Strangely enough it did not effect my Flarum installation at all, but I guess it uses its own session management etc.
