### ISSUE TITLE
Marketplace not working within Atheos

### ISSUE THREAD

**Issue by baddiedev** [Atheos/Atheos#286]
**Describe the bug**
When I install a new copy of Atheos on to a sub domain on my shared server, I'm not able to access the Atheos Marketplace from the right side menu. I control many domains in my hosting reseller account and I tend to install a copy of Atheos on a sub domain of each so that I can get quick and easy access to edit any file in the domain. When I try to access the marketplace from within Atheos to install a few useful plugins like Beautify or MiniMap, the marketplace popup has no content.
Whatever is causing this seems to be doing the same for the Update Check content too

**To Reproduce**
SSH into shared server. Git clone Atheos to subdomain folder. Change permissions on /data, /plugins, /theme, /workspace. Navigate to subdomain for first time and install. Click Marketplace in right side menu.

**Expected behavior**
The marketplace popup should contain links to plugins etc from Atheos marketplace for easy install

**Screenshots**
![image](https://github.com/Atheos/Atheos/assets/38323743/69ce3341-df96-47a2-b28c-9e33d0cb86ae)
![image](https://github.com/Atheos/Atheos/assets/38323743/8b7f0645-5c27-437f-88be-0ecd5d8c6334)

**Desktop (please complete the following information):**
 - OS: ChromeOS
 - Browser Chrome
 - Version 124

**Additional context**
If memory serves, I'm pretty sure that this has been mentioned before, and the issue is something to do with settings somewhere, like PHP or in my Server. I have tried to locate this info so I didn't have to bother you with the query, but I've come up with nothing.

**Comment by HLSiira** [comment]
Do you have any errors in the browser or server logs?
