### ISSUE TITLE
Can't complete setup on nginx with php-fpm

### ISSUE THREAD

**Issue by crazy-logic** [Atheos/Atheos#292]
Hey all, 

bit of a weird one - have a host with Nginx and PHP8.3 (FPM) and i can't get past the Initial Setup page. 

i've checked my php-fpm and nginx with some custom php scripts, i can create files and directories from php, so it's unlikely a file permission problem (i think). 

when filling out and then pressing the install button i get the following in the address bar 

"http://IP/a/?username=matt&password=xxx&validate=xxx&projectName=dev&projectPath=dev&domain=&development=true&analytics=true&timezone=Pacific%2FMidway"

and the page returns to a blank initial setup state. no DIR's are created in the workspace dir, and the config.php file contains no infomation/is blank. 

Where should i go next to trouble shoot this?

**Comment by HLSiira** [comment]
That is indeed a weird one; sadly I don't have an nginx environment to tinker with, so you'll have to work with me a bit.

I'm assuming that you removed your IP address from that URL. Do you have have error or access logs that might have some clues?

Overall there shouldn't be anything in your address bar, the javascript should be catching any form submissions and redirecting them to ajax posts, so I'm curious if the browser console is showing you any missing scripts or resources.
