### ISSUE TITLE
Filebrowser

### ISSUE THREAD

**Issue by kurim** [Atheos/Atheos#32]
The fa-plus don't get replaced by fa-minus

close:
![Anmerkung 2020-02-16 132606](https://user-images.githubusercontent.com/1880220/74604609-ef2e8380-50bf-11ea-9377-12e68e10fb97.png)
open:
![Anmerkung 2020-02-16 132606-](https://user-images.githubusercontent.com/1880220/74604610-f05fb080-50bf-11ea-982e-9e2d8aad3770.png)

**Comment by HLSiira** [comment]
Yeah the file-manager is my next project, but I'm honestly procrastinating on it. That file is rough; I'll try to fix it today if I can.

**Comment by HLSiira** [comment]
Hey Kurim, I fixed it in the most recent commits that I made in the Dev version, but I have rewrote massive parts of Atheos in this version and I don't think it's super stable right now. I know for a fact that I broke a lot of plugins, and only just barely managed to keep the CodeGit working with the update.

**Comment by HLSiira** [comment]
Hey Kurim, I think I fixed this in the latest dev stuff. I'm going to push to master because reasons; let me know what you think.

**Comment by kurim** [comment]
Sadly it seems to be broken.

apache log:
```
Uncaught ArgumentCountError: Too few arguments to function Filemanager::respond(), 0 passed in /components/filemanager/class.filemanager.php on line 169 and exactly 1 expected in 
/components/filemanager/class.filemanager.php:572
Stack trace:
/components/filemanager/class.filemanager.php(169): Filemanager->respond()
/components/filemanager/controller.php(61): Filemanager->index()
{main}\n  thrown in /components/filemanager/class.filemanager.php on line 572'
```
Chromedebug log
![image](https://user-images.githubusercontent.com/1880220/75047921-f1318180-54c7-11ea-8c3f-5a4c81b2e7ec.png)

I already do a full reinstall of master branch

**Comment by HLSiira** [comment]
Is this with the most recent push to master?

**Comment by kurim** [comment]
Yes,
do you need some more infos? About use system?

**Comment by HLSiira** [comment]
Yeah if you know what you did in Atheos to cause the error, and can tell me how to recreate the bug, that'd be cool

**Comment by kurim** [comment]
System:
> Ubuntu Linux 18.04.2 (Linux 4.15.0-76-generic auf x86_64)
> Apache 2.4
> PHP 7.4.3 (fpm)

I have clean the folder where it is currently installed (w/o data + config.php), copy all files to it set the owner to www-data

Project path is absolute (/home/kurim/public_html/sensor.kurim.de) for example.
If i open a Project it happens, and the filebrowser dont show anything.

![image](https://user-images.githubusercontent.com/1880220/75091899-bc2e3900-5572-11ea-9335-1b6db58fa9d5.png)

**Comment by HLSiira** [comment]
Might have fixed it in this most recent push to master

**Comment by kurim** [comment]
Yes works fine.
Thanks
