### ISSUE TITLE
Fresh install on QNAP  NAS with firmware 4.4.x

### ISSUE THREAD

**Issue by ozett** [Atheos/Atheos#38]
install run fine, but i cannot create files  or folders.

any hint? thx.

 (i come [from your hint](https://github.com/Codiad/Codiad/issues/1120#issuecomment-594251441) for a successor of codiad here 😄 👍  )

![image](https://user-images.githubusercontent.com/5937811/75857455-8bfa5c00-5df6-11ea-96d4-ac90a4afb83f.png)

**Comment by ozett** [comment]
the first projectfolder was created during install and has permission issues.
i created now another one. this one works.

![image](https://user-images.githubusercontent.com/5937811/75858202-feb80700-5df7-11ea-83d1-35aeba8a8fe3.png)

**Comment by ozett** [comment]
i  want to edit the files in my webshare (like i am used to do it with codiad),
so i used the abs-path option. but it did not work. why? what to do?

![image](https://user-images.githubusercontent.com/5937811/75858361-56ef0900-5df8-11ea-8623-0a1b8498336d.png)

![image](https://user-images.githubusercontent.com/5937811/75858373-5ce4ea00-5df8-11ea-9447-bc2fdb18c41f.png)

**Comment by ozett** [comment]
manual edit of the projects.php did help.

![image](https://user-images.githubusercontent.com/5937811/75858818-383d4200-5df9-11ea-9935-b35973de184f.png)

**Comment by ozett** [comment]
manual fiddling with  the projects.php helps to come to good results.
(maybe all different issues to adress in the code?)

![image](https://user-images.githubusercontent.com/5937811/75859184-d6c9a300-5df9-11ea-9e57-3f63438507c0.png)

**Comment by HLSiira** [comment]
I'm having a little trouble following the issue here so I'm going to guess a little bit and hope you can fill in the blanks.
You've made 3 projects so far, however test3 was made with an absolute path and it is not working correctly. My first guess is that one of the other two projects was made with an absolute path as well. Atheos, like Codiad, only allows 1 project to have an absolute path and I haven't had cause to change it yet.

Does that sound like it could be the issue?

Either way, I'll look into it tonight, I did a huge rewrite of the project creation system recently and might have made a mistake.

Let me know if anything changes, thank you.

**Comment by ozett** [comment]
thanks for looking after my errros.
1) the  project  which  was created  with the install was blocked. no abs-path.
i could not create  files.

2) but after install  i  created project2. and i created  files. no abs-path.
working good. but could not rename.

3) i tried to create a project with absolute path. was not possible. got errors (see screenshots)

4) i edited the project.php manually. 
i created  a project with absolut path. working fine.
i renamed projects. working fine.
i edited the path of  the first project from the install to  "." working fine.

but to make this everything (create files, rename projects, set abs-paht) with the gui/webpage gave me errors.

---sidenote
i like the default color-scheme. can i look this up/edit somehow easily?

**Comment by HLSiira** [comment]
The default color scheme is a work in progress, I'm trying to focus on using the color scheme from https://clrs.cc/ but with a darker background, but it's slow going.

Mmm I'll have to play around with it then. Hopefully I'll be able to fix it tonight.

For the first project, were you trying to create an ABS path project and it failed?

**Comment by ozett** [comment]
first project was only name.
second project also.
project with abs-path failed.
a project with abs-path was working fine on my qnap only with manual edit . but that worked.

i am watching your github project. so i can try new version an report, if you like

**Comment by HLSiira** [comment]
Merp.

I probably broke something on the creation methods. I'll update you here when I feel like I've covered all my bases for a fix. Let me know if you run into any other issues.

**Comment by HLSiira** [comment]
So correction, I actually haven't messed with the project creation component yet, and I'm realizing that I think you can only create an absolute path during installation. I'm going to keep working on this but I'm not sure this is necessary a bug/issue so much as a feature I need to add; if that makes sense.

**Comment by ozett** [comment]
one thing in the install is a bug: as i created only a projectname during install (remember: no! abs.-path, only name) i could not create files in this project. i can check this again with a fresh install, if you like.

**Comment by HLSiira** [comment]
Nah you don't have to. I'll look into it, but it shouldn't have done anything differently that Codiad originally did. I haven't messed with the project files very much but maybe I missed something.

**Comment by HLSiira** [comment]
Hey, I hope you don't mind me taking my time on this issue. I haven't had much time recently to code and am trying to finish up some of the other parts of Atheos I'm working on before tackling this issue, but it is on my mind.

Please let me know if that doesn't work for you or if you need a fix sooner rather than later.

**Comment by ozett** [comment]
its somehow now basically working for me.
so i will keep subscribed to this thread and get informed if you put here any updates on code-changes. 
thanks for looking into this 👍

**Comment by HLSiira** [comment]
Hey ozett,
I have been thinking about your issue and reading more on how qnap works. I'm starting to think that this might not be an issue with Atheos, but rather qnap has more strict file permissions than default Linux.

I'm curious what the permissions and user/groups are for the files and folders of your web root.

If you're curious, this is a really thorough write up of what permissions _should_ look like for an apache/linux server: https://serverfault.com/a/357109

This might not be an issue that I can fix with Atheos, but I might be able to put more checks and eventually try to add better error messages.

**Comment by ozett** [comment]
hi, thanks for noting the basic principle of linux file permission for the webserver on qnap.
your idee for checking this before install an giving hints to fix them pre-install would be helpful.

i would have checked out the latest github today to give a new test, but as my version-check says that i am on the latest version, i think there is nothing new to this today.

give me a shout here to test something new on the qnap.
+1

**Comment by HLSiira** [comment]
I completed a rewrite of the project component for the latest push to master. I'm pretty sure I would have removed anything preventing a proper project creation, but qnap still might run differently than I expect it to. I'm going to mark this as fixed and close this issue, but if you're still having issues, let me know and I'll reopen.

Sorry it took so long to get back to you on this.
