### ISSUE TITLE
Some Buttons are broken

### ISSUE THREAD

**Issue by kurim** [Atheos/Atheos#50]
I have done a clean install.

And some buttons are not shown correctly

![1](https://user-images.githubusercontent.com/1880220/77893645-769d1400-7274-11ea-86c9-67929d62405a.png)
![2](https://user-images.githubusercontent.com/1880220/77893647-7735aa80-7274-11ea-90e8-93aa8b6b9902.png)
![3](https://user-images.githubusercontent.com/1880220/77893651-77ce4100-7274-11ea-91a1-b1c2b695c857.png)

Also but this should be a new ticket, Git integration is a bit broken since Remotes, Push/Pull and User Config shows the same content for me

**Comment by HLSiira** [comment]
Alright fixed the weird buttons not showing up. (Hopefully)

I also rewrote the marketplace and the update components yesterday, they need a few more hours of work though, but hopefully all the issues with that will be solved in a release later today.

The Git issues might take a little longer to take care of, as the CodeGit plugin and now component is one of the worst offenders of bad code I've come across in Atheos so far and its' really taking a long time to fix.

**Comment by kurim** [comment]
Thank you Siira,
also can you provide the new english language strings, then I will do the missing german parts.

**Comment by WebCrew** [comment]
The Git Plugin is super old and had even some problems with good old Codiad times. In the meantime, the GIT API has been renewed / updated several times and the Codiad plugin just got very harsh and botched updates - at least as I remember it.

I wanted to take the opportunity to say **thank you** @HLSiira for bringing **Codiad** back to life. I love this simple IDE - it's so easy to use and easy to integrate. I have already installed it in 2 CMS systems as a type of backend template editor and was really sad that **Codiad** was no longer being developed.

So **thank you again** and the **very best** for the future.
Greetings from Germany,

Andy

**Comment by HLSiira** [comment]
The main issue with Codegit is that it's a massively large plugin and it was programmed in an insanely complicated way, which has made it incredibly slow going on fixing it.

Thanks man, that means a lot, I hope it works out for you and any bugs you find, please open an issue, and I'll do my best to fix them.

**Comment by HLSiira** [comment]
I've fixed the buttons, the language files are probably going to be a persistent issue as I've lost track of all the places I've broken them, but I've gotten better about adding ones that are needed.

I'm going to open the Codegit as a separate issue and close this one since the CodeGit is going to take me a long time to really nail down. It's a very very complicated component.
