### ISSUE TITLE
Filenames with spaces

### ISSUE THREAD

**Issue by fsatzger** [Atheos/Atheos#56]
Files with spaces in name cannot be opened. No error message is shown.

Atheos 4.0.1

Apache 2.4.25 + PHP 7.0.33 on Debian 9

**Comment by HLSiira** [comment]
Roger doger, I'll try to fix this tomorrow if I can.

**Comment by HLSiira** [comment]
This issue should be fixed in the latest dev push, but that branch could have some bugs as I had to play around with the file manager a bit and I'm not completely done rewriting it, but at least this issue should be fixed.
