### ISSUE TITLE
Broken tutorial links

### ISSUE THREAD

**Issue by psociety** [Atheos/Atheos#59]
Hi!
First of all: thank you for creating and keeping up this IDE! I'm another user that comes from an abandoned IDE (C9).

1. I'm looking at all steps before starting the setup and it seems that all links from "Tutorial" section at https://www.atheos.io/docs/installation , point/show the index content :O

2. Stupid detail but feels strange to see a blue colored text that is not a link ("(Optional Installation Settings)", "nsure that the following have write capabilities", etc..) :)

**Comment by HLSiira** [comment]
Sorry about that, I had a typo on the links and fixed them, let me know if you find anymore, or if you have any issues.

And now that you've pointed that out, I can't help but to agree lol. I'll try to do a little redesigning on the site.
