### ISSUE TITLE
Cannot scroll down

### ISSUE THREAD

**Issue by r0bin123** [Atheos/Atheos#60]
Does anyone know why I can't scroll down when I enter http://127.0.0.1?

**Comment by kurim** [comment]
So you run Atheos on you local machine, or where do you enter the address?

**Comment by r0bin123** [comment]
I run Atheos on my Ubuntu vm.

**Comment by HLSiira** [comment]
Can you attach some screenshots of the issue you're having?

**Comment by HLSiira** [comment]
I'm going to close this issue as r0bin123 hasn't replied to add more detail to the issue.
