### ISSUE TITLE
"All fields must be filled out" when all fields are already filled

### ISSUE THREAD

**Issue by psociety** [Atheos/Atheos#61]
I'm sorry to be back again :(
![image](https://user-images.githubusercontent.com/29523682/80245157-77a24500-866a-11ea-874a-44a3de985b29.png)

All data is filled yet that popup appears. Right after it, i get a second one saying "Do you really want to create project with absolute path "..."?"

By that second message it seems to fail to pick the project name somewhere, but i may be wrong.

Edit: it seems that the problem is this selector being too generic:
```js
$('input').each(function () {
   if ($(this).val() == '' && $(this).attr('name') != 'path') {
      empty_fields = true;
   }
 });
```

Since the detected empty field is 
```html
<input id="cip-genpw-textfield-password" type="text" class="cip-genpw-textfield">
```
which i don't even see because it's in a modal/dialog (it's from a browser extension), not in the form.

Maybe switching to `required` attribute would be a better idea?(https://www.w3schools.com/tags/att_input_required.asp)

**Comment by HLSiira** [comment]
No problem at all, I'd rather you make an issue than be stuck with a bug.

Let me do a fresh install and I'll try to see what the problem is.

**Comment by HLSiira** [comment]
Let me know if the latest push to master fixed the issue for you.

**Comment by psociety** [comment]
Yes! it did!
