### ISSUE TITLE
Some Javascript errors

### ISSUE THREAD

**Issue by kurim** [Atheos/Atheos#70]
Version: latest git version

![image](https://user-images.githubusercontent.com/1880220/80872628-603f0980-8cb3-11ea-8077-e9a2a3100c94.png)

Any suggestion how to solve?

**Comment by HLSiira** [comment]
Yeah I think I know what the issue is, I can put up a fix in few hours.

I think it's too do with the market assuming that it has a cache when it hasn't made one yet.

-------- Original Message --------

**Comment by kurim** [comment]
Yes its better but not totaly fixed cause atheos.io/market/json does not exist.

![image](https://user-images.githubusercontent.com/1880220/80909981-d16ed300-8d2c-11ea-8680-85c1e70b1d57.png)

**Comment by HLSiira** [comment]
Hey Kurim, is this error still popping up for you?

**Comment by kurim** [comment]
Hey Siira,

it's gone - case closed

**Comment by HLSiira** [comment]
Cool, let me know if there is anything you need me to work on, I'm getting close to being finished with the full update of Atheos so some feature requests will be handy.
