### ISSUE TITLE
Unable to complete installation or log in first time

### ISSUE THREAD

**Issue by willfull** [Atheos/Atheos#73]
Installed Atheos on my server following the instructions.  This is an Ubuntu 16.04 server running NGINX and PHP-FPM 7.3.  Downloaded the app using git, ensured that the ownership and permissions were correct, and then set it up the server block in NGINX.  AFAIK, it's correct.

When I visit the site for the first time, I am presented with the screen showing the dependency check, user registration, and prompt for project name/folder etc.  I fill everything out.  When I click submit, nothing happens.  When I peek inside the folder, the config.php file is populated, as well as some of the .json files in /data.  However, that's as far as I go.  Now, if I happen to reload the site, I'm presented with the standard user login for Atheos.  If I type in the user/pass that I entered from the setup, it doesn't do anything except display the notification "Username not found".  (It's probably worth mentioning the same thing used to happen with me when I installed Codiad.)

Update:  I used a different username this time, all lower-case, and interestingly enough I can login.  I still have the issue with the setup getting hung up, but at least I can log in now and activate settings through the IDE interface.

**Comment by HLSiira** [comment]
To start with, I'm not super familiar with Nginx but it doesn't sound like that's the issue. Can you tell me what characters you used in your initial username? You don't have to tell me the username, just any special characters.

When I started working on the install and user components of Codiad, I found out that Codiad by default filters out a good number of characters from the username. It's closer to asking for your actual name instead, but it doesn't impart that on the user at all.

I'm willing to bet that there is a silent failure on my part when I changed that.

If you're curious about more info on it while I try to debug, all your user data is stored in a file in the data folder.

I'm sorry you ran into trouble installing it, please let me know if you run into any other issues and I'll try to fix them as soon as possible.

-------- Original Message --------

**Comment by HLSiira** [comment]
@willfull Are you still having trouble with the installation?
