### ISSUE TITLE
How do I save my settings?

### ISSUE THREAD

**Issue by wh33t** [Atheos/Atheos#78]
I prefer to use soft tabs and only 2 of them at a time. I can't seem to figure out how to save these settings. I think in Codiad there was a save settings button but it doesn't appear for me. 

I'm using FireFox 76.0.1

**Comment by HLSiira** [comment]
Yeah there is a save button in Codiad, however in Atheos, every change should be automatically saved as you make them, so I removed the save button since it didn't serve a purpose. Are your changes not taking affect?

**Comment by wh33t** [comment]
It doesn't appear to save. Should I see an animation or something indicating that a save is taking place?

Here is a link to screen cap.
https://send.firefox.com/download/6b29b67e31ba608a/#9K7eVKcQMbaiiY6FtBIMnw

**Comment by HLSiira** [comment]
No, you shouldn't as it is currently, but I'm adding a save toast message right now. I didn't even think about user feedback when I changed how the settings worked. The new feedback should be in the next push to dev branch in a few minutes.

Are the changes you're trying to make taking affect in the editor though?

**Comment by wh33t** [comment]
> Are the changes you're trying to make taking affect in the editor though?

I never actually tested until right now.

It appears the tab size is saved, but it doesn't appear to be tabbing as space characters. Soft tabs should mean space characters right?

**Comment by HLSiira** [comment]
I think so. I've never messed with the setting myself but I'll double check the code to see if something is wrong.

**Comment by wh33t** [comment]
Please let me know when and where I can download the updates!

**Comment by HLSiira** [comment]
I'll work on it first thing in the morning, however the feedback will be added to the master branch here in a few minutes.

**Comment by HLSiira** [comment]
So I think when using Soft tabs, Ace Editor emulates cursor movement as though they were tabs still, however the actual text is still spaces. If you switch to soft tabs, then press tab, moving left and right over it will cause the cursor to jump as though it's a tab; however if you highlight it, it acts like individual spaces.

**Comment by wh33t** [comment]
Excellent. So it's working in Aetheos correctly, the settings window just doesn't seem to update the changes?

**Comment by HLSiira** [comment]
No, it should be working all together now in the latest release, but it'd be for you to tell me that it's not working. Classic "it works on my machine moment here".

**Comment by wh33t** [comment]
Issue is fixed. Toast message is a nice touch. Shall I close?
