### ISSUE TITLE
Who uses Atheos IDE?

### ISSUE THREAD

**Issue by HLSiira** [Atheos/Atheos#80]
In an effort to better understand and provide for whoever regularly uses Atheos, can you please tell me what you use it for, what features you want, shortcomings you experience, or just anything you feel I should look into or consider changing?

I've been working on Atheos for a while and in all honesty, I'm running out of ideas on what improvements to make. I know Codegit needs to be finished and I am working on it slowly; it's an awful component to work on, but aside from that, I've been the sole controller of Atheos and I don't want to push it in a direction without knowing what people want from it.

**Comment by wh33t** [comment]
I'm an off and on contracted back end developer. I haven't built a full project for a client from scratch to completion in a long time, but I used to do it frequently. Now I mostly use Codiad (Atheos now) to write scripts in PHP that will be executed during cron to do maintenance on machines such as triggering rsync backups and the like but I'm about to start a bunch of personal projects with it. 

One thing I always wished Codiad would do for me is code completion. Like if I type in str_ I would love for Atheos to bring up a drown down list of the built in functions in php that start with str_ like many other editors will do. And the ultimate hope of mine is that somehow I could tell Atheos where my own custom functions are and Atheos could perform code completion and hinting for them as well. In the code completion/hinting it would also show me the correct syntax such as $needle, $haystack just like the PHP documentation does, if this could work for my own functions it would be GG, I'd never look for another editor again. 

Another thing that would be excellent is if it let me mouse over a function (whether PHP built in, or my own) and let me ALT+Click on it and it would take me to the official PHP documentation for that function or would open up the script where my function is declared. I want this so bad. 

Any chances any of that could be implemented?

**Comment by kurim** [comment]
I use Atheos mainly for working on my website since I like to test the result directly w/o upload to the server, as local IDE I use VSCode since I love the look and feel.

Maybe you can add phpcbf to make sure the written code is up to standard

**Comment by HLSiira** [comment]
@wh33t The snippet / suggestion is actually a feature in the latest release, should be on by default but I'll double check just in case something is wrong. Adding your own snippets / functions isn't terribly hard, but it's more like hacking it yourself rather than an easy to use feature, but it might not be hard to add a custom snippet method. I'll have to look into the Alt+Click for the docs. That does sound like a cool feature.


@kurim So instead of just linting the code, you want a way to enforce certain code standards? That might be doable. I've managed to integrate a few other PHP libraries so it's possible, but it depends on the library and how well written the docs are for it.

**Comment by wh33t** [comment]
I would probably be willing to pay some money to have those features implemented. Would that help motivate that direction?

**Comment by HLSiira** [comment]
@wh33t That's not necessary, I've looked into it a little bit and I think it's definitely possible; however it's going to take some time. There are some comments on a few of the Ace forums about people making similar things and succeeding, so it should be possible.

**Comment by WebCrew** [comment]
I use it for projects like CMS development and Plugin development mostly in PHP. I also was using Codiad integrated as a plugin in a CMS as a type of themes editor.

**Comment by HLSiira** [comment]
Alright, this answers my question pretty well. Thank you.

**Comment by phpcoinn** [comment]
PHPCoin project use it as IDE for building smart contracts. We integrated our custom side panel to existing functionality.
https://atheos.phpcoin.net/
