### ISSUE TITLE
Language Support

### ISSUE THREAD

**Issue by HLSiira** [Atheos/Atheos#87]
How well does the multi language support work?

As an English speaker, I can only speculate as to how well it works, but I've tried it on a few occasions and it doesn't seem to work well at all.
The language support system has no considerations for adding more options via plugin, nor does it really function as well as it should. I'm pretty sure it's set up extremely over complicated for how well it doesn't seem to work.

**Comment by kurim** [comment]
Hi Siira,

I like to have it in native language but for some things it make no sense to have it native language.

So if it is to complex to take it you may drop it.

But if you keep it language support for plugins, should be on plugin creator duty just for base langeuage (eng) and provide a clean file to allow other ppl to translate it.

**Comment by HLSiira** [comment]
What kind of things don't make sense for native language?

**Comment by kurim** [comment]
Like special words which are define by specific tools ex. git pull/push should not be translated, the normal menu things are fine.

They are sure more things which don’t make sense if you translate them.

**Comment by HLSiira** [comment]
Complete rebuild of the language system. Language files are now in the components/i18n folder. Still some lots of work to do though

**Comment by kurim** [comment]
Small Suggestion,
how about an autodetection based on Browser language?
Currently it is only:
forcedLang & SESSION

May it can extend with $_SERVER['HTTP_ACCEPT_LANGUAGE'] for auto detect.

**Comment by HLSiira** [comment]
Funnily enough, the library I used as a base had that exact thing and I removed it because I didn't think it was important. Consider it added back in

-------- Original Message --------

**Comment by kurim** [comment]
By the way, would it not be better to have it like:

```php
<?php i18n('xyz') ?>
```
instead of
```php
<?php echo i18n('xyz') ?>
```
To reduce the amount of using echo?

Also I like the new implementation, it make the translation file more readable.

**Comment by HLSiira** [comment]
Google Translate? Lol, that's what I used when I was in school a lot.

It would be a lot more preferred to not have to keep typing Echo, but there are a good few spots where you don't want to echo and only want the returned values and I haven't thought of a good way to do that aside from just having two separate functions.

**Comment by kurim** [comment]
I does not mean the translation it self, by the way https://www.deepl.com/translator is way better :)

I Mean to import the json to do the translation, like this:

![image](https://user-images.githubusercontent.com/1880220/84927047-92be8d80-b0cc-11ea-9299-7e4dafcd53e0.png)

I know there are many online translation tools maybe some of them can beused.

**Comment by HLSiira** [comment]
Oh, I enjoy this json editor, seems pretty reasonable and viable. Not sure it meets your needs

-------- Original Message --------

**Comment by kurim** [comment]
> Oh, I enjoy this json editor, seems pretty reasonable and viable. Not sure it meets your needs

Which one do you mean? the i18n-manager?

Regarding this:
```php
<?php i18n('xyz') ?>
```

how about:
This is echo:
```php
<?php i18n('xyz') ?>
```
This is return:
```php
<?php i18n('xyz', true) ?>
```
or another "option" to get the return instead of echo

**Comment by HLSiira** [comment]
https://jsoneditoronline.org/

I don't think I pasted the link lol

That's similar to how the old one worked and I liked it, but i18n actually accepts two parameters already, for phrases that accept file names and such, like "Project %s loaded" will replace the %s with a project name.

I thought about having it be three variables and just sending null if you don't need the parameter part but idk, I couldn't think of there was a better solution or not

-------- Original Message --------

**Comment by HLSiira** [comment]
I'm comfortable with where the language system is at and am going to close this.
