### ISSUE TITLE
Atheos Market - CORS Error

### ISSUE THREAD

**Issue by kurim** [Atheos/Atheos#89]
With current dev vesion I got the following error:

> Access to XMLHttpRequest at 'https://atheos.io/market/json' from origin 'https://ide.****.de' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by HLSiira** [comment]
Can you repeat what you did?

I'm looking at the Atheos marketplace site and it's Access Control Allow Origin Policy seems to be set up correctly, nor can I get the error to recreate itself on my end.

**Comment by kurim** [comment]
I just login to my atheos and got the error on the chrome debugger

**Comment by HLSiira** [comment]
Would you be able to screen shot the stack trace?

**Comment by kurim** [comment]
you mean this:

![image](https://user-images.githubusercontent.com/1880220/86401882-428a2280-bcab-11ea-9dba-e98099d4411a.png)

**Comment by HLSiira** [comment]
I'm going to have to think about this for a while. I'm not really sure what could be the issue. Is it causing a dead stop in use of Atheos?

-------- Original Message --------

**Comment by kurim** [comment]
No, but you can't use the Market with this issue.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

If you add this to header on marketplace: Access-Control-Allow-Origin: * it will work, I think it make no sense to add every Atheos client side

**Comment by HLSiira** [comment]
That's the funny thing though. That is already on the marketplace site

**Comment by kurim** [comment]
Strange, still not gone

**Comment by HLSiira** [comment]
I'm starting to think that maybe your components.min.js in the public folder isn't being updated correctly. I did a fresh install of Atheos and didn't get the error at all, did a third party test of the CORS policy on Atheos marketplace and couldn't replicate the error. I'm at a loss of what could be causing it; aside from potentially having an old config file with an older URL but that hasn't changed in weeks.

**Comment by kurim** [comment]
I delete every thing except the class. from public, but it does nto solve the problem

**Comment by HLSiira** [comment]
Do you remember about 6 months ago you put a pull request in to change https://atheos.io to https://www.atheos.io? I think we're having that issue again. I used [this link](https://www.test-cors.org/#?client_method=GET&client_credentials=false&server_url=https%3A%2F%2Fwww.atheos.io%2Fmarket%2Fjson&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) to test the cors policy. If I use www, it works, if I don't, it fails.

On the dev version of Atheos though, everything should be pointing to the www version, so I'm curious why your install doesn't.

Let me know if you can find out why and if that fixes the issue.

**Comment by kurim** [comment]
Yes that fix the issue, may be the base of my version was from stable to dev.

Reason could be that https://atheos.io/market/json forward to https://www.atheos.io/market/json

**Comment by HLSiira** [comment]
So it's the fault of my domain registrar. They should be ashamed of themselves.

**Comment by kurim** [comment]
Since we found it, it's fine.
