### ISSUE TITLE
PHP version 

### ISSUE THREAD

**Issue by swatrigant** [Atheos/Atheos#90]
Hello !

I've read on the Atheos website that to run Atheos you only need PHP 5+, but I noticed that the Null Coalesce Operator "??" was used in Atheos (for exemple on line 302 in common.php), even if it only appeared in php 7.0. 

Are they any other php 7 things in Atheos ? Can it actually run on a php 5+ server once the "??" are removed ?

Thanks a lot for your help !

**Comment by HLSiira** [comment]
I'm actually not sure. I can only think of "?:" off the top of my head, but sad to say I didn't think about PHP compatibility nearly as much as I thought about browser compatibility. 

I can spend some of today combing through the files and see what I find.

**Comment by HLSiira** [comment]
Hey @swatrigant,

I pushed a new version to master, it has a TON of changes, but most importantly, I got it to work on a PHP 5.4 install on Windows, hopefully that fixes the issue. Let me know how it works for you.

**Comment by kurim** [comment]
Hi,

just as a hint PHP 5 is unsupported by The PHP Group

https://www.php.net/eol.php
https://www.php.net/supported-versions.php

So to have it compatible to an EOL Version should not be necessary.
Just my opinion.

**Comment by HLSiira** [comment]
Mmm, I didn't think about that. Well, either way I only had to remove the ?? in a few places in order to fix the issue, so not a huge time commitment.

Probably won't put much effort into supporting PHP5 if that's the case but if someone asks, I'm not opposed.

**Comment by kurim** [comment]
Hm change it might be good, but may be should switch to official support 7.x to make it more clear.
Since 5.x is EOL and may be unsecure it should not be used anymore

**Comment by HLSiira** [comment]
Good point. Changed the website to reflect official recommendation to use PHP7, but still included that it has been shown to work on PHP5.4.
