### ISSUE TITLE
Support for PHP7

### ISSUE THREAD

**Issue by ScrumpyJack** [Atheos/Atheos#99]
Should I expect Atheos to work with PHP7? 
I'm getting all sorts of issue, for example creating an initial project, or using codegit.

**Comment by kurim** [comment]
Hello ScrumpyJack,
it works fine under PHP 7.4.
I have it running on a Ubuntu 18.04 with Apache and PHP Version 7.4.7.

Regarding the Issues can you describe them?

**Comment by ScrumpyJack** [comment]
Thanks for your question.
Here is what happens

Fresh git clone https://github.com/Atheos/Atheos

Create the user and enter Project Name and Path.  I create a project called "name" with a path of "path".

When you log in, the Project and Path appear in the UI, the File Manager and Project list both show "name"

but ...

```
ls /var/www/Atheos/workspace/
README.md

cat /var/www/Atheos/data/projects.json
{
    "": "name"
}
```

**Comment by ScrumpyJack** [comment]
As an aside, it would be nice to have the Project Name to appear in the Projects browser, and the Project Path to appear in the File Manager. Currently for me, the value of "Project Name" is used in both

**Comment by kurim** [comment]
I have try to dublicate the issue, but i can not reproduce it, I create a "test" with "test",
i think it is folder right issue, can you check the owner of your atheos folder?
Since you clone it from git it may not owned by www-data user (or what ever your server uses)

That it shows both time Project Name is intended, because if you use the absolute version the value will be to big.
But i think a mouse over or something might be possible what do you think @HLSiira

**Comment by ScrumpyJack** [comment]
Yes, permissions are fine, I changed them before creating the user and project.

I works fine for every subsequent project I create, so if you are trying to reproduce, start from scratch.

For the Project Name, you could always strip the absolute path before the last dir, but I would rather disable the ability to chose an absolute path and only have projects with a relative path.

**Comment by kurim** [comment]
I found the root cause, and created a PR https://github.com/Atheos/Atheos/pull/100

you need to replace in line 103 of /components/install/process.php

```php
$projectPath = str_replace(" ", "_", preg_replace('/[^\w-\.]/', '', $projectPath));
```
```php
$projectPath = str_replace(" ", "_", preg_replace('/[^\w\-\.]/', '', $projectPath));
```

Than it works fine

**Comment by ScrumpyJack** [comment]
We spotted. Thanks

**Comment by clach04** [comment]
I'm able to edit and the git integration  works well enough for my needs (diff'ing). I'm using nginix and:

    # php --version
    PHP 7.0.33-0+deb9u8 (cli) (built: Jul  5 2020 06:34:50) ( NTS )
    Copyright (c) 1997-2017 The PHP Group
    Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
        with Zend OPcache v7.0.33-0+deb9u8, Copyright (c) 1999-2017, by Zend Technologies
